<?php
if ( ! function_exists( 'deep_kses' )) {
	function deep_kses() {
		return array(
			'a' => array(
				'href' => array(),
				'title' => array(),
				'target' => array(),
				'style' => array(),
				'class' => array(),
			),
			'br' => array(),
			'em' => array(),
			'strong' => array(),
			'span' => array(
				'class' => array(),
			),
		);
	}
}
vc_map( array(
	'name'			=> esc_html__( 'Icon Box', 'deep' ),
	'base'			=> 'iconbox',
	'description'	=> esc_html__( 'Icon + text article', 'deep' ),
	'icon'			=> 'webnus-iconbox',
	'category'		=> esc_html__( 'Webnus Shortcodes', 'deep' ),
	'params'		=> array(
		array(
			'type' => 'dropdown',
			'heading' => esc_html__( 'Pre build types', 'deep' ),
			'param_name' => 'type',
			'value' => array(
				'Type 0' =>'0',
				'Type 1' =>'1',
				'Type 2' =>'2',
				'Type 3' =>'3',
				'Type 4' =>'4',
				'Type 5' =>'5',
				'Type 6' =>'6',
				'Type 7' =>'7',
				'Type 8' =>'8',
				'Type 9' =>'9',
				'Type 10'=>'10',
				'Type 11'=>'11',
				'Type 12'=>'12',
				'Type 13'=>'13',
				'Type 14'=>'14',
				'Type 15'=>'15',
				'Type 16'=>'16',
				'Type 17'=>'17',
				'Type 18'=>'18',
				'Type 19'=>'19',
				'Type 20'=>'20',
				'Type 21'=>'21',
				'Type 22'=>'22',
				'Type 23'=>'23',
				'Type 24'=>'24',
				'Type 25'=>'25',
				'Type 26'=>'26',
				'Type 27'=>'27',
				'Type 28'=>'28',
				'Type 29'=>'29',
				'Type 30'=>'30',
			),
			'admin_label' => true,
			'description' => wp_kses( __( 'You can choose from these pre-designed types. <a href="http://deeptem.com/features/boxes-elements/icon-boxes/" target="_blank">View All Types</a>', 'deep'), deep_kses() ),
		),
		array(
			'type'			=> 'checkbox',
			'heading'		=> esc_html__( 'Tilte Effect', 'deep' ),
			'param_name'	=> 'tilteffect',
			'value'			=> array( esc_html__( 'Yes', 'deep' ) => 'yes' ),
		),
		array(
			'type'				=> 'dropdown',
			'heading'			=> esc_html__( 'Background Color type', 'deep' ),
			'param_name'		=> 'iconbox_color_type',
			'value'				=> array(
				'Solid color'	=> 'iconbox-solid-color',
				'Gradient'		=> 'iconbox_gradient',
			),
			'std'				=> 'iconbox-solid-color'
		),
		array(
			'type'			=> 'colorpicker',
			'heading'		=> esc_html__( 'Background Color', 'deep' ),
			'param_name'	=> 'background_color',
			'value'			=> '',
			'description'	=> esc_html__( 'Select Icon box Background Color', 'deep'),
			'dependency'	=> array(
				'element'	=> 'iconbox_color_type',
				'value'		=> 'iconbox-solid-color',
			),
		),
		array(
			'type'				=> 'colorpicker',
			'heading'			=> esc_html__('color 1', 'deep'),
			'param_name'		=> 'iconbox_grad_color_1',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
			'dependency'		=> array(
				'element'	=> 'iconbox_color_type',
				'value'		=> 'iconbox_gradient',
			),
		),
		array(
			'type'				=> 'colorpicker',
			'heading'			=> esc_html__('color 2', 'deep'),
			'param_name'		=> 'iconbox_grad_color_2',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
			'dependency'		=> array(
				'element'	=> 'iconbox_color_type',
				'value'		=> 'iconbox_gradient',
			),
		),
		array(
			'type'				=> 'colorpicker',
			'heading'			=> esc_html__('color 3', 'deep'),
			'param_name'		=> 'iconbox_grad_color_3',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
			'dependency'		=> array(
				'element'	=> 'iconbox_color_type',
				'value'		=> 'iconbox_gradient',
			),
		),
		array(
			'type'				=> 'colorpicker',
			'heading'			=> esc_html__('color 4', 'deep'),
			'param_name'		=> 'iconbox_grad_color_4',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
			'dependency'		=> array(
				'element'	=> 'iconbox_color_type',
				'value'		=> 'iconbox_gradient',
			),
		),
		array(
			'type'			=> 'textfield',
			'heading'		=> esc_html__( 'Direction', 'deep' ),
			'param_name'	=> 'iconbox_grad_direction',
			'value'			=> '',
			'description'	=> esc_html__( 'Gradient direction example: 70', 'deep'),
			'dependency'	=> array(
				'element'	=> 'iconbox_color_type',
				'value'		=> 'iconbox_gradient',
			),
		),
		array(
			'type'				=> 'dropdown',
			'heading'			=> esc_html__( 'Hover Background Color type', 'deep' ),
			'param_name'		=> 'iconbox_color_type_hover',
			'value'				=> array(
				'Solid color'	=> 'iconbox-solid-color_hover',
				'Gradient'		=> 'iconbox_gradient_hover',
			),
			'std'				=> 'iconbox-solid-color_hover'
		),
		array(
			'type'			=> 'colorpicker',
			'heading'		=> esc_html__( 'Hover Background Color', 'deep' ),
			'param_name'	=> 'background_color_hover',
			'value'			=> '',
			'description'	=> esc_html__( 'Select Icon box  Hover Background Color', 'deep'),
			'dependency'	=> array(
				'element'	=> 'iconbox_color_type_hover',
				'value'		=> 'iconbox-solid-color_hover',
			),
		),
		array(
			'type'				=> 'colorpicker',
			'heading'			=> esc_html__('color 1', 'deep'),
			'param_name'		=> 'iconbox_grad_color_1_hover',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
			'dependency'		=> array(
				'element'	=> 'iconbox_color_type_hover',
				'value'		=> 'iconbox_gradient_hover',
			),
		),
		array(
			'type'				=> 'colorpicker',
			'heading'			=> esc_html__('color 2', 'deep'),
			'param_name'		=> 'iconbox_grad_color_2_hover',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
			'dependency'		=> array(
				'element'	=> 'iconbox_color_type_hover',
				'value'		=> 'iconbox_gradient_hover',
			),
		),
		array(
			'type'				=> 'colorpicker',
			'heading'			=> esc_html__('color 3', 'deep'),
			'param_name'		=> 'iconbox_grad_color_3_hover',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
			'dependency'		=> array(
				'element'	=> 'iconbox_color_type_hover',
				'value'		=> 'iconbox_gradient_hover',
			),
		),
		array(
			'type'				=> 'colorpicker',
			'heading'			=> esc_html__('color 4', 'deep'),
			'param_name'		=> 'iconbox_grad_color_4_hover',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
			'dependency'		=> array(
				'element'	=> 'iconbox_color_type_hover',
				'value'		=> 'iconbox_gradient_hover',
			),
		),
		array(
			'type'			=> 'textfield',
			'heading'		=> esc_html__( 'Direction', 'deep' ),
			'param_name'	=> 'iconbox_grad_direction_hover',
			'value'			=> '',
			'description'	=> esc_html__( 'Gradient direction example: 70', 'deep'),
			'dependency'	=> array(
				'element'	=> 'iconbox_color_type_hover',
				'value'		=> 'iconbox_gradient_hover',
			),
		),
		array(
			"type" => "checkbox",
			"heading" => esc_html__( "Align", 'deep' ),
			"description" => esc_html__( "Please choose align, Left or Right", 'deep'),
			"param_name" => "align",
			"value" => array(
				esc_html__( "Left", 'deep' ) 	=> 'left',
				esc_html__( "right", 'deep' ) 	=> 'right',
			),
			"dependency"	=> array( 
				'element'	=> 'type',
				'value'		=> '18',
			),
		),
		array(
			'type'			=> 'checkbox',
			'heading'		=> esc_html__( 'Featured Iconbox ?', 'deep' ),
			'param_name'	=> 'featured',
			'value'			=> array( esc_html__( 'Yes', 'deep' ) => ' w-featured' ),
			'description'	=> esc_html__( 'Iconbox Featured Plan', 'deep'),
			'dependency'	=> array(
				'element'	=> 'type',
				'value'		=> '22',
			),
		),
		array(
			'type'			=> 'checkbox',
			'heading'		=> esc_html__( 'Remove right border?', 'deep' ),
			'param_name'	=> 'border_right',
			'value'			=> array( esc_html__( 'Yes', 'deep' ) => ' w-border-right' ),
			'dependency'	=> array(
				'element'	=> 'type',
				'value'		=> array( '15', '22', ),
			),
		),

		// Title Group
		array(
			'group'			=> 'Title',
			'type'			=> 'textfield',
			'heading'		=> esc_html__('Title', 'deep'),
			'param_name'	=> 'icon_title',
			'value'			=> '',
			'description'	=> esc_html__( 'IconBox Title', 'deep')
		),
		array(
			'group'				=> 'Title',
			'type'				=> 'textfield',
			'heading'			=> esc_html__( 'Title font size', 'deep' ),
			'param_name'		=> 'icon_title_font_size',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-6 wn-px',
		),
		array(
			'group'				=> 'Title',
			'type'				=> 'textfield',
			'heading'			=> esc_html__( 'Title font weight', 'deep' ),
			'param_name'		=> 'icon_title_font_weight',
			'value'				=> '',
			'description'		=> esc_html__( 'Example: 100,200,300,400,500,600,700,800,900', 'deep'),
			'edit_field_class'	=> 'vc_col-sm-6',
		),
		array(
			'group'			=> 'Title',
			'type'			=> 'radio',
			'heading'		=> esc_html__('Alignment', 'deep'),
			'param_name'	=> 'icon_title_align',
			'value'			=> '',
			'options'		=> array(
				'left'		=> 'left',
				'center'	=> 'center',
				'right'		=> 'right',
			),
			'edit_field_class'	=> 'vc_col-sm-6',
		),
		array(
			'group'				=> 'Title',
			'type'				=> 'radio',
			'heading'			=> esc_html__('Font Style', 'deep'),
			'param_name'		=> 'icon_title_font_style',
			'value'				=> '',
			'options'			=> array(
				'normal'		=> 'normal',
				'italic'		=> 'italic',
				'underline'		=> 'underline',
			),
			'edit_field_class'	=> 'vc_col-sm-6 wn-font-style',
		),
		array(
			'group'				=> esc_html__( 'Title', 'deep' ),
			'type'				=> 'dropdown',
			'heading'			=> esc_html__( 'Color type', 'deep' ),
			'param_name'		=> 'title_color_type',
			'value'				=> array(
				'Solid color'	=> 'title-solid-color',
				'Gradient'		=> 'title_gradient',
			),
			'std'				=> 'title-solid-color'
		),
		array(
			'group'			=> 'Title',
			'type'			=> 'colorpicker',
			'heading'		=> esc_html__('Title color (leave bank for default color)', 'deep'),
			'param_name'	=> 'title_color',
			'value'			=> '',
			'description'	=> esc_html__( 'Select title color', 'deep'),
			'dependency'	=> array(
				'element'	=> 'title_color_type',
				'value'		=> 'title-solid-color',
			),
		),
		array(
			'group'				=> esc_html__( 'Title', 'deep' ),
			'type'				=> 'colorpicker',
			'heading'			=> esc_html__('color 1', 'deep'),
			'param_name'		=> 'title_grad_color_1',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
			'dependency'		=> array(
				'element'	=> 'title_color_type',
				'value'		=> 'title_gradient',
			),
		),
		array(
			'group'				=> esc_html__( 'Title', 'deep' ),
			'type'				=> 'colorpicker',
			'heading'			=> esc_html__('color 2', 'deep'),
			'param_name'		=> 'title_grad_color_2',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
			'dependency'		=> array(
				'element'	=> 'title_color_type',
				'value'		=> 'title_gradient',
			),
		),
		array(
			'group'				=> esc_html__( 'Title', 'deep' ),
			'type'				=> 'colorpicker',
			'heading'			=> esc_html__('color 3', 'deep'),
			'param_name'		=> 'title_grad_color_3',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
			'dependency'		=> array(
				'element'	=> 'title_color_type',
				'value'		=> 'title_gradient',
			),
		),
		array(
			'group'				=> esc_html__( 'Title', 'deep' ),
			'type'				=> 'colorpicker',
			'heading'			=> esc_html__('color 4', 'deep'),
			'param_name'		=> 'title_grad_color_4',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
			'dependency'		=> array(
				'element'	=> 'title_color_type',
				'value'		=> 'title_gradient',
			),
		),
		array(
			'group'			=> esc_html__( 'Title', 'deep' ),
			'type'			=> 'textfield',
			'heading'		=> esc_html__( 'Direction', 'deep' ),
			'param_name'	=> 'title_grad_direction',
			'value'			=> '',
			'description'	=> esc_html__( 'Gradient direction example: 70', 'deep'),
			'dependency'	=> array(
				'element'	=> 'title_color_type',
				'value'		=> 'title_gradient',
			),
		),
		array(
			'group'				=> esc_html__( 'Title', 'deep' ),
			'type'				=> 'dropdown',
			'heading'			=> esc_html__( 'Hover Color type', 'deep' ),
			'param_name'		=> 'title_color_type_hover',
			'value'				=> array(
				'Solid color'	=> 'title-solid-color_hover',
				'Gradient'		=> 'title_gradient_hover',
			),
			'std'				=> 'title-solid-color_hover'
		),
		array(
			'group'			=> 'Title',
			'type'			=> 'colorpicker',
			'heading'		=> esc_html__('Title Hover color (leave bank for default color)', 'deep'),
			'param_name'	=> 'title_color_hover',
			'value'			=> '',
			'description'	=> esc_html__( 'Select title color', 'deep'),
			'dependency'	=> array(
				'element'	=> 'title_color_type_hover',
				'value'		=> 'title-solid-color_hover',
			),
		),
		array(
			'group'				=> esc_html__( 'Title', 'deep' ),
			'type'				=> 'colorpicker',
			'heading'			=> esc_html__('color 1', 'deep'),
			'param_name'		=> 'title_grad_color_1_hover',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
			'dependency'		=> array(
				'element'	=> 'title_color_type_hover',
				'value'		=> 'title_gradient_hover',
			),
		),
		array(
			'group'				=> esc_html__( 'Title', 'deep' ),
			'type'				=> 'colorpicker',
			'heading'			=> esc_html__('color 2', 'deep'),
			'param_name'		=> 'title_grad_color_2_hover',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
			'dependency'		=> array(
				'element'	=> 'title_color_type_hover',
				'value'		=> 'title_gradient_hover',
			),
		),
		array(
			'group'				=> esc_html__( 'Title', 'deep' ),
			'type'				=> 'colorpicker',
			'heading'			=> esc_html__('color 3', 'deep'),
			'param_name'		=> 'title_grad_color_3_hover',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
			'dependency'		=> array(
				'element'	=> 'title_color_type_hover',
				'value'		=> 'title_gradient_hover',
			),
		),
		array(
			'group'				=> esc_html__( 'Title', 'deep' ),
			'type'				=> 'colorpicker',
			'heading'			=> esc_html__('color 4', 'deep'),
			'param_name'		=> 'title_grad_color_4_hover',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
			'dependency'		=> array(
				'element'	=> 'title_color_type_hover',
				'value'		=> 'title_gradient_hover',
			),
		),
		array(
			'group'			=> esc_html__( 'Title', 'deep' ),
			'type'			=> 'textfield',
			'heading'		=> esc_html__( 'Direction', 'deep' ),
			'param_name'	=> 'title_grad_direction_hover',
			'value'			=> '',
			'description'	=> esc_html__( 'Gradient direction example: 70', 'deep'),
			'dependency'	=> array(
				'element'	=> 'title_color_type_hover',
				'value'		=> 'title_gradient_hover',
			),
		),


		array(
			'group'			=> esc_html__( 'Title', 'deep' ),
			'type'			=> 'checkbox',
			'heading'		=> esc_html__( 'Use theme default font family?', 'deep' ),
			'param_name'	=> 'title_theme_fonts',
			'value'			=> array( esc_html__( 'Yes', 'deep' ) => 'yes' ),
			'description'	=> esc_html__( 'Use font family from the theme.', 'deep' ),
			'std'			=> 'yes',
		),
		array(
			'group'			=> esc_html__( 'Title', 'deep' ),
			'type'			=> 'google_fonts',
			'param_name'	=> 'title_text_font',
			'value'			=> '',
			'settings'		=> array(
				'fields'	=> array(
					'font_family_description' => esc_html__( 'Select font family.', 'deep' ),
					'font_style_description'  => esc_html__( 'Select font styling.', 'deep' ),
				),
			),
			'dependency'	=> array(
				'element'				=> 'title_theme_fonts',
				'value_not_equal_to'	=> 'yes',
			),
		),
		
		// Title Border
		array(
			'group'			=> esc_html__( 'Title', 'deep' ),
			'type'			=> 'dropdown',
			'heading'		=> esc_html__( 'Border', 'deep' ),
			'param_name'	=> 'icon_title_border',
			'value'			=> array(
				'none'		=> 'none',		
				'dotted'	=> 'dotted',		
				'dashed'	=> 'dashed',		
				'solid'		=> 'solid',		
				'double'	=> 'double',		
				'groove'	=> 'groove',		
				'ridge'		=> 'ridge',		
				'inset'		=> 'inset',		
				'outset'	=> 'outset',		
			),
		),
		array(
			'group'				=> 'Title',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('border top', 'deep'),
			'param_name'		=> 'title_bord_top',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element'	=> 'icon_title_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),
		array(
			'group'				=> 'Title',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('border right', 'deep'),
			'param_name'		=> 'title_bord_right',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element'	=> 'icon_title_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),
		array(
			'group'				=> 'Title',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('border bottom', 'deep'),
			'param_name'		=> 'title_bord_bottom',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element'	=> 'icon_title_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),
		array(
			'group'				=> 'Title',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('border left', 'deep'),
			'param_name'		=> 'title_bord_left',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element'	=> 'icon_title_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),
		array(
			'group'				=> 'Title',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('border top left radius', 'deep'),
			'param_name'		=> 'title_bord_top_left_radius',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element'	=> 'icon_title_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),
		array(
			'group'				=> 'Title',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('border top right radius', 'deep'),
			'param_name'		=> 'title_bord_top_right_radius',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element'	=> 'icon_title_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),
		array(
			'group'				=> 'Title',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('border bottom left radius', 'deep'),
			'param_name'		=> 'title_bord_bottom_left_radius',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element'	=> 'icon_title_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),
		array(
			'group'				=> 'Title',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('border bottom right radius', 'deep'),
			'param_name'		=> 'title_bord_bottom_right_radius',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element'	=> 'icon_title_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),
		array(
			'group'			=> 'Title',
			'type'			=> 'colorpicker',
			'heading'		=> esc_html__('Border color', 'deep'),
			'param_name'	=> 'title_border_color',
			'value'			=> '',
			'description'	=> esc_html__( 'Select border color (leave blank for default color)', 'deep'),
			'dependency'	=> array(
				'element'	=> 'icon_title_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),

		array(
			'group'				=> 'Title',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Padding top', 'deep'),
			'param_name'		=> 'title_pad_top',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
		),
		array(
			'group'				=> 'Title',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Padding right', 'deep'),
			'param_name'		=> 'title_pad_right',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
		),
		array(
			'group'				=> 'Title',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Padding bottom', 'deep'),
			'param_name'		=> 'title_pad_bottom',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
		),
		array(
			'group'				=> 'Title',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Padding left', 'deep'),
			'param_name'		=> 'title_pad_left',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
		),
		array(
			'group'				=> 'Title',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Margin top', 'deep'),
			'param_name'		=> 'title_marg_top',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
		),
		array(
			'group'				=> 'Title',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Margin right', 'deep'),
			'param_name'		=> 'title_marg_right',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
		),
		array(
			'group'				=> 'Title',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Margin bottom', 'deep'),
			'param_name'		=> 'title_marg_bottom',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
		),
		array(
			'group'				=> 'Title',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Margin left', 'deep'),
			'param_name'		=> 'title_marg_left',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
		),
		array(
			'group'			=> 'Subtitle',
			'type'			=> 'textfield',
			'heading'		=> esc_html__('Subtitle', 'deep'),
			'param_name'	=> 'icon_subtitle',
			'value'			=> '',
			'description'	=> esc_html__( 'IconBox Subtitle', 'deep'),
			'dependency'	=> array(
				'element' => 'type',
				'value'	=> array( '1', '15', '21', ),
			),
		),
		array(
			'group'				=> 'Subtitle',
			'type'				=> 'textfield',
			'heading'			=> esc_html__( 'Subtitle font size', 'deep' ),
			'param_name'		=> 'icon_subtitle_font_size',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-12 wn-px',
			'dependency'	=> array(
				'element' => 'type',
				'value'	=> array( '1', '15', '21', ),
			),
		),
		array(
			'group'			=> 'Subtitle',
			'type'			=> 'radio',
			'heading'		=> esc_html__('Font Style', 'deep'),
			'param_name'	=> 'icon_subtitle_font_style',
			'value'			=> '',
			'options'		=> array(
				'normal'	=> 'normal',
				'italic'	=> 'italic',
				'underline'	=> 'underline',
			),
			'edit_field_class'	=> 'vc_col-xs-6 wn-font-style',
			'dependency'	=> array(
				'element' => 'type',
				'value'	=> array( '1', '15', '21', ),
			),
		),
		array(
			'group'			=> 'Subtitle',
			'type'			=> 'radio',
			'heading'		=> esc_html__('Alignment', 'deep'),
			'param_name'	=> 'icon_subtitle_align',
			'value'			=> '',
			'options'		=> array(
				'left'		=> 'left',
				'center'	=> 'center',
				'right'		=> 'right',
			),
			'dependency'	=> array(
				'element' => 'type',
				'value'	=> array( '1', '15', '21', ),
			),
			'edit_field_class'	=> 'vc_col-xs-6',
		),
		array(
			'group'			=> esc_html__( 'Subtitle', 'deep' ),
			'type'			=> 'checkbox',
			'heading'		=> esc_html__( 'Use theme default font family?', 'deep' ),
			'param_name'	=> 'subtitle_theme_fonts',
			'value'			=> array( esc_html__( 'Yes', 'deep' ) => 'yes' ),
			'description'	=> esc_html__( 'Use font family from the theme.', 'deep' ),
			'std'			=> 'yes',
			'dependency'	=> array(
				'element' => 'type',
				'value'	=> array( '1', '15', '21', ),
			),
		),
		array(
			'group'			=> esc_html__( 'Subtitle', 'deep' ),
			'type'			=> 'google_fonts',
			'param_name'	=> 'subtitle_text_font',
			'value'			=> '',
			'settings'		=> array(
				'fields'	=> array(
					'font_family_description' => esc_html__( 'Select font family.', 'deep' ),
					'font_style_description'  => esc_html__( 'Select font styling.', 'deep' ),
				),
			),
			'dependency'	=> array(
				'element'				=> 'subtitle_theme_fonts',
				'value_not_equal_to'	=> 'yes',
			),
		),

		// Subtitle Border
		array(
			'group'			=> esc_html__( 'Subtitle', 'deep' ),
			'type'			=> 'dropdown',
			'heading'		=> esc_html__( 'Border', 'deep' ),
			'param_name'	=> 'icon_subtitle_border',
			'value'			=> array(
				'none'		=> 'none',		
				'dotted'	=> 'dotted',		
				'dashed'	=> 'dashed',		
				'solid'		=> 'solid',		
				'double'	=> 'double',		
				'groove'	=> 'groove',		
				'ridge'		=> 'ridge',		
				'inset'		=> 'inset',		
				'outset'	=> 'outset',		
			),
			'dependency'	=> array(
				'element' => 'type',
				'value'	=> array( '1', '15', '21', ),
			),
		),
		array(
			'group'				=> 'Subtitle',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('border top', 'deep'),
			'param_name'		=> 'subtitle_bord_top',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element'	=> 'icon_subtitle_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),
		array(
			'group'				=> 'Subtitle',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('border right', 'deep'),
			'param_name'		=> 'subtitle_bord_right',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element'	=> 'icon_subtitle_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),
		array(
			'group'				=> 'Subtitle',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('border bottom', 'deep'),
			'param_name'		=> 'subtitle_bord_bottom',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element'	=> 'icon_subtitle_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),
		array(
			'group'				=> 'Subtitle',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('border left', 'deep'),
			'param_name'		=> 'subtitle_bord_left',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element'	=> 'icon_subtitle_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),
		array(
			'group'				=> 'Subtitle',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('border top left radius', 'deep'),
			'param_name'		=> 'subtitle_bord_top_left_radius',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element'	=> 'icon_subtitle_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),
		array(
			'group'				=> 'Subtitle',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('border top right radius', 'deep'),
			'param_name'		=> 'subtitle_bord_top_right_radius',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element'	=> 'icon_subtitle_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),
		array(
			'group'				=> 'Subtitle',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('border bottom left radius', 'deep'),
			'param_name'		=> 'subtitle_bord_bottom_left_radius',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element'	=> 'icon_subtitle_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),
		array(
			'group'				=> 'Subtitle',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('border bottom right radius', 'deep'),
			'param_name'		=> 'subtitle_bord_bottom_right_radius',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element'	=> 'icon_subtitle_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),
		array(
			'group'				=> 'Subtitle',
			'type'			=> 'colorpicker',
			'heading'		=> esc_html__('Border color', 'deep'),
			'param_name'	=> 'subtitle_border_color',
			'value'			=> '',
			'description'	=> esc_html__( 'Select border color (leave blank for default color)', 'deep'),
			'dependency'	=> array(
				'element'	=> 'icon_subtitle_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),
		array(
			'group'				=> 'Subtitle',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Padding top', 'deep'),
			'param_name'		=> 'subtitle_pad_top',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element' => 'type',
				'value'	=> array( '1', '15', '21', ),
			),
		),
		array(
			'group'				=> 'Subtitle',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Padding right', 'deep'),
			'param_name'		=> 'subtitle_pad_right',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element' => 'type',
				'value'	=> array( '1', '15', '21', ),
			),
		),
		array(
			'group'				=> 'Subtitle',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Padding bottom', 'deep'),
			'param_name'		=> 'subtitle_pad_bottom',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element' => 'type',
				'value'	=> array( '1', '15', '21', ),
			),
		),
		array(
			'group'				=> 'Subtitle',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Padding left', 'deep'),
			'param_name'		=> 'subtitle_pad_left',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element' => 'type',
				'value'	=> array( '1', '15', '21', ),
			),
		),
		array(
			'group'				=> 'Subtitle',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Margin top', 'deep'),
			'param_name'		=> 'subtitle_marg_top',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element' => 'type',
				'value'	=> array( '1', '15', '21', ),
			),
		),
		array(
			'group'				=> 'Subtitle',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Margin right', 'deep'),
			'param_name'		=> 'subtitle_marg_right',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element' => 'type',
				'value'	=> array( '1', '15', '21', ),
			),
		),
		array(
			'group'				=> 'Subtitle',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Margin bottom', 'deep'),
			'param_name'		=> 'subtitle_marg_bottom',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element' => 'type',
				'value'	=> array( '1', '15', '21', ),
			),
		),
		array(
			'group'				=> 'Subtitle',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Margin left', 'deep'),
			'param_name'		=> 'subtitle_marg_left',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element' => 'type',
				'value'	=> array( '1', '15', '21', ),
			),
		),
		array(
			'group'			=> 'Content',
			'type'			=> 'textarea',
			'heading'		=> esc_html__('Content', 'deep'),
			'param_name'	=> 'iconbox_content',
			'value'			=> '',
			'description'	=> esc_html__( 'IconBox Content Goes Here', 'deep'),
		),
		array(
			'group'			=> 'Content',
			'type'			=> 'textfield',
			'heading'		=> esc_html__('Content font size', 'deep'),
			'param_name'	=> 'iconbox_content_size',
			'value'			=> '',
			'edit_field_class'	=> 'vc_col-xs-4 wn-px',
		),
		array(
			'group'			=> 'Content',
			'type'			=> 'radio',
			'heading'		=> esc_html__('Font Style', 'deep'),
			'param_name'	=> 'icon_content_font_style',
			'value'			=> '',
			'options'		=> array(
				'normal'	=> 'normal',
				'italic'	=> 'italic',
				'underline'	=> 'underline',
			),
			'edit_field_class'	=> 'vc_col-xs-4 wn-font-style',
		),
		array(
			'group'			=> 'Content',
			'type'			=> 'radio',
			'heading'		=> esc_html__('Alignment', 'deep'),
			'param_name'	=> 'icon_content_align',
			'value'			=> '',
			'options'		=> array(
				'left'		=> 'left',
				'center'	=> 'center',
				'right'		=> 'right',
			),
			'edit_field_class'	=> 'vc_col-xs-4',
		),
		array(
			'group'			=> esc_html__( 'Content', 'deep' ),
			'type'			=> 'checkbox',
			'heading'		=> esc_html__( 'Use theme default font family?', 'deep' ),
			'param_name'	=> 'content_theme_fonts',
			'value'			=> array( esc_html__( 'Yes', 'deep' ) => 'yes' ),
			'description'	=> esc_html__( 'Use font family from the theme.', 'deep' ),
			'std'			=> 'yes',
		),
		array(
			'group'			=> esc_html__( 'Content', 'deep' ),
			'type'			=> 'google_fonts',
			'param_name'	=> 'content_text_font',
			'value'			=> '',
			'settings'		=> array(
				'fields'	=> array(
					'font_family_description' => esc_html__( 'Select font family.', 'deep' ),
					'font_style_description'  => esc_html__( 'Select font styling.', 'deep' ),
				),
			),
			'dependency'	=> array(
				'element'				=> 'content_theme_fonts',
				'value_not_equal_to'	=> 'yes',
			),
		),
		array(
			'group'			=> 'Content',
			'type'			=> 'colorpicker',
			'heading'		=> esc_html__('Content color (leave bank for default color)', 'deep'),
			'param_name'	=> 'content_color',
			'value'			=> '',
			'description'	=> esc_html__( 'Select content color', 'deep'),
			'edit_field_class'	=> 'vc_col-xs-6',
		),
		array(
			'group'			=> 'Content',
			'type'			=> 'colorpicker',
			'heading'		=> esc_html__('Hover content color (leave bank for default color)', 'deep'),
			'param_name'	=> 'content_color_hover',
			'value'			=> '',
			'description'	=> esc_html__( 'Select content color', 'deep'),
			'edit_field_class'	=> 'vc_col-xs-6',
		),

		// Content Border
		array(
			'group'			=> esc_html__( 'Content', 'deep' ),
			'type'			=> 'dropdown',
			'heading'		=> esc_html__( 'Border', 'deep' ),
			'param_name'	=> 'icon_content_border',
			'value'			=> array(
				'none'		=> 'none',		
				'dotted'	=> 'dotted',		
				'dashed'	=> 'dashed',		
				'solid'		=> 'solid',		
				'double'	=> 'double',		
				'groove'	=> 'groove',		
				'ridge'		=> 'ridge',		
				'inset'		=> 'inset',		
				'outset'	=> 'outset',		
			),
		),
		array(
			'group'				=> 'Content',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('border top', 'deep'),
			'param_name'		=> 'content_bord_top',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element'	=> 'icon_content_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),
		array(
			'group'				=> 'Content',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('border right', 'deep'),
			'param_name'		=> 'content_bord_right',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element'	=> 'icon_content_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),
		array(
			'group'				=> 'Content',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('border bottom', 'deep'),
			'param_name'		=> 'content_bord_bottom',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element'	=> 'icon_content_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),
		array(
			'group'				=> 'Content',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('border left', 'deep'),
			'param_name'		=> 'content_bord_left',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element'	=> 'icon_content_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),
		array(
			'group'			=> 'Content',
			'type'			=> 'colorpicker',
			'heading'		=> esc_html__('Border color', 'deep'),
			'param_name'	=> 'content_border_color',
			'value'			=> '',
			'description'	=> esc_html__( 'Select border color (leave blank for default color)', 'deep'),
			'dependency'	=> array(
				'element'	=> 'icon_content_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),
		array(
			'group'				=> 'Content',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Padding top', 'deep'),
			'param_name'		=> 'content_pad_top',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
		),
		array(
			'group'				=> 'Content',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Padding right', 'deep'),
			'param_name'		=> 'content_pad_right',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
		),
		array(
			'group'				=> 'Content',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Padding bottom', 'deep'),
			'param_name'		=> 'content_pad_bottom',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
		),
		array(
			'group'				=> 'Content',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Padding left', 'deep'),
			'param_name'		=> 'content_pad_left',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
		),
		array(
			'group'				=> 'Content',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Margin top', 'deep'),
			'param_name'		=> 'content_marg_top',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
		),
		array(
			'group'				=> 'Content',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Margin right', 'deep'),
			'param_name'		=> 'content_marg_right',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
		),
		array(
			'group'				=> 'Content',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Margin bottom', 'deep'),
			'param_name'		=> 'content_marg_bottom',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
		),
		array(
			'group'				=> 'Content',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Margin left', 'deep'),
			'param_name'		=> 'content_marg_left',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
		),
		array(
			'type'			=> 'dropdown',
			'heading'		=> esc_html__( 'Background Image Position', 'deep' ),
			'param_name'	=> 'bg_img_pos',
			'value'			=> array(
				'Top Left Position'		=>'tlp',
				'Top Right Position'	=>'trp',
				'Bottom Left Position'	=>'blp',
				'Bottom Right Position' =>'brp',
			),
			'dependency'	=> array( 
				'element'	=> 'type',
				'value'		=> '28',
			),
			'description' => esc_html__( 'You can choose Background Image Position.', 'deep'),
		),
		array(
			'group'			=> esc_html__( 'Link', 'deep' ),
			'type'			=> 'textfield',
			'heading'		=> esc_html__('Link Text', 'deep'),
			'param_name'	=> 'icon_link_text',
			'value'			=> '',
			'description'	=> esc_html__( 'IconBox Link Text', 'deep'),
			'edit_field_class'	=> 'vc_col-sm-12',
		),
		array(
			'group'			=> esc_html__( 'Link', 'deep' ),
			'type'			=> 'textfield',
			'heading'		=> esc_html__('Link URL', 'deep'),
			'param_name'	=> 'icon_link_url',
			'value'			=> '',
			'description'	=> esc_html__( 'IconBox Link URL (http://example.com)', 'deep'),
			'edit_field_class'	=> 'vc_col-sm-12',
		),
		array(
			'group'			=> esc_html__( 'Link', 'deep' ),
			'type'			=> 'checkbox',
			'heading'		=> __( 'Open link in a new tab? ', 'deep' ),
			'description'	=> __( 'Add Target = _blank', 'deep'),
			'param_name'	=> 'link_target',
			'std'			=> 'false',
			'edit_field_class'	=> 'vc_col-sm-6',
		),
		array(
			'group'			=> esc_html__( 'Link', 'deep' ),
			'type'			=> 'radio',
			'heading'		=> esc_html__('Link text alignment', 'deep'),
			'param_name'	=> 'icon_link_align',
			'value'			=> '',
			'options'		=> array(
				'left'		=> 'left',
				'center'	=> 'center',
				'right'		=> 'right',
			),
			'edit_field_class'	=> 'vc_col-sm-6',
		),
		array(
			'group'			=> esc_html__( 'Link', 'deep' ),
			'type'			=> 'colorpicker',
			'heading'		=> esc_html__('Link color (leave bank for default color)', 'deep'),
			'param_name'	=> 'link_color',
			'value'			=> '',
			'description'	=> esc_html__( 'Select link color', 'deep'),
		),
		array(
			'group'			=> esc_html__( 'Link', 'deep' ),
			'type'			=> 'checkbox',
			'heading'		=> __( 'Title linkable', 'deep' ),
			'description'	=> __( 'Add Link to title', 'deep'),
			'param_name'	=> 'title_linkable',
			'std'			=> 'false',
			'edit_field_class'	=> 'vc_col-sm-6',
		),
		array(
			'group'			=> esc_html__( 'Link', 'deep' ),
			'type'			=> 'checkbox',
			'heading'		=> __( 'Icon box linkable', 'deep' ),
			'description'	=> __( 'By activating this option read more and icon link will be disabled.', 'deep'),
			'param_name'	=> 'box_linkable',
			'std'			=> 'false',
			'edit_field_class'	=> 'vc_col-sm-6',
		),
		array(
			'type'			=> 'radio',
			'heading'		=> esc_html__( 'Make title and icon/image side by side', 'deep' ),
			'param_name'	=> 'side_by_side_title_icon',
			'value'			=> '',
			'options'		=> array(
				'none'		=> 'none',
				'left'		=> 'left',
				'right'		=> 'right',
			),
		),

		array(
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Padding top', 'deep'),
			'param_name'		=> 'pad_top',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
		),
		array(
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Padding right', 'deep'),
			'param_name'		=> 'pad_right',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
		),
		array(
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Padding bottom', 'deep'),
			'param_name'		=> 'pad_bottom',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
		),
		array(
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Padding left', 'deep'),
			'param_name'		=> 'pad_left',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
		),
		array(
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Margin top', 'deep'),
			'param_name'		=> 'marg_top',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
		),
		array(
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Margin right', 'deep'),
			'param_name'		=> 'marg_right',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
		),
		array(
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Margin bottom', 'deep'),
			'param_name'		=> 'marg_bottom',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
		),
		array(
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Margin left', 'deep'),
			'param_name'		=> 'marg_left',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
		),

		// Iconbox Border
		array(
			'type'			=> 'dropdown',
			'heading'		=> esc_html__( 'Border', 'deep' ),
			'param_name'	=> 'icon_box_border',
			'value'			=> array(
				'none'		=> 'none',		
				'dotted'	=> 'dotted',		
				'dashed'	=> 'dashed',		
				'solid'		=> 'solid',		
				'double'	=> 'double',		
				'groove'	=> 'groove',		
				'ridge'		=> 'ridge',		
				'inset'		=> 'inset',		
				'outset'	=> 'outset',		
			),
		),
		array(
			'type'				=> 'textfield',
			'heading'			=> esc_html__('border top', 'deep'),
			'param_name'		=> 'iconbox_bord_top',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element'	=> 'icon_box_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),
		array(
			'type'				=> 'textfield',
			'heading'			=> esc_html__('border right', 'deep'),
			'param_name'		=> 'iconbox_bord_right',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element'	=> 'icon_box_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),
		array(
			'type'				=> 'textfield',
			'heading'			=> esc_html__('border bottom', 'deep'),
			'param_name'		=> 'iconbox_bord_bottom',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element'	=> 'icon_box_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),
		array(
			'type'				=> 'textfield',
			'heading'			=> esc_html__('border left', 'deep'),
			'param_name'		=> 'iconbox_bord_left',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element'	=> 'icon_box_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),
		array(
			'type'				=> 'textfield',
			'heading'			=> esc_html__('border top left radius', 'deep'),
			'param_name'		=> 'iconbox_bord_top_left_radius',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
		),
		array(
			'type'				=> 'textfield',
			'heading'			=> esc_html__('border top right radius', 'deep'),
			'param_name'		=> 'iconbox_bord_top_right_radius',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
		),
		array(
			'type'				=> 'textfield',
			'heading'			=> esc_html__('border bottom left radius', 'deep'),
			'param_name'		=> 'iconbox_bord_bottom_left_radius',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
		),
		array(
			'type'				=> 'textfield',
			'heading'			=> esc_html__('border bottom right radius', 'deep'),
			'param_name'		=> 'iconbox_bord_bottom_right_radius',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
		),
		array(
			'type'			=> 'colorpicker',
			'heading'		=> esc_html__('Border color', 'deep'),
			'param_name'	=> 'iconbox_border_color',
			'value'			=> '',
			'description'	=> esc_html__( 'Select border color (leave blank for default color)', 'deep'),
			'dependency'	=> array(
				'element'	=> 'icon_box_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),
		array(
			'type'			=> 'textfield',
			'heading'		=> esc_html__('Minimum Background Color Height', 'deep'),
			'param_name'	=> 'min_height',
			'value'			=> '',
			'description'	=> esc_html__( 'Height size in px format, Example: 250px', 'deep'),
			'dependency'	=> array(
				'element' 	=> 'type',
				'value'		=> '26',
			),
		),
		array(
			'type'			=> 'colorpicker',
			'heading'		=> esc_html__('Icon Background Color', 'deep'),
			'param_name'	=> 'icon_bg',
			'value'			=> '',
			'description'	=> esc_html__( 'Select Icon Background Color', 'deep'),
			'dependency'	=> array(
				'element' 	=> 'type',
				'value'		=> '26',
			),
		),
		array(
			'type'			=> 'attach_image',
			'heading'		=> esc_html__( 'Background Image', 'deep' ),
			'param_name'	=> 'background_image',
			'value'			=> '',
			'description'	=> esc_html__( 'Select Image to Background the icon box.', 'deep'),
			'dependency'	=> array(
				'element' 	=> 'type',
				'value'	=> '30',
			),
		),
		// Icon or Image
		array(
			'group'			=> 'icon/image',
			'type'			=> 'dropdown',
			'heading'		=> esc_html__( 'Icon or image', 'deep' ),
			'param_name'	=> 'icon_or_image',
			'value'			=> array(
				'Icon'	=> 'icon',		
				'Image'	=> 'image',		
			),
			'description'	=> esc_html__( 'Select shortcode type', 'deep'),
			'std' 			=> 'icon',
		),
		array(
			'group'			=> 'icon/image',
			'type'			=> 'attach_image',
			'heading'		=> esc_html__( 'Pick an image', 'deep' ),
			'param_name'	=> 'icon_image',
			'value'			=> '',
			'description'	=> wp_kses( __( 'Select Image instead of Icons.<br>Note: If you have another Icon that not is here. You can put PNG image of that instead of these Icons.', 'deep'), array( 'br' => array() ) ),
			'dependency'	=> array( 'element' => 'icon_or_image', 'value' => 'image' ),
		),
		array(
			'group'			=> 'icon/image',
			'type'			=> 'textfield',
			'heading'		=> esc_html__( 'Image Size', 'deep' ),
			'param_name'	=> 'thumbnail',
			'value'			=> '',
			'description'	=> esc_html__( 'Enter image size (Example: 200x100 (Width x Height)).', 'deep'),
			'dependency'	=> array( 'element' => 'icon_or_image', 'value' => 'image' ),
		),
		array(
			'group'				=> 'icon/image',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Icon Size (leave blank for default size)', 'deep'),
			'param_name'		=> 'icon_size',
			'value'				=> '',
			'dependency'		=> array( 'element' => 'icon_or_image', 'value' => 'icon' ),
			'edit_field_class'	=> 'vc_col-sm-12 wn-px',
		),
		array(
			'group'				=> esc_html__( 'icon/image', 'deep' ),
			'type'				=> 'dropdown',
			'heading'			=> esc_html__( 'Color type', 'deep' ),
			'param_name'		=> 'icon_color_type',
			'value'				=> array(
				'Solid color'	=> 'icon-solid-color',
				'Gradient'		=> 'icon_gradient',
			),
			'std'				=> 'icon-solid-color',
			'dependency'	=> array( 'element' => 'icon_or_image', 'value' => 'icon' ),
		),
		array(
			'group'			=> esc_html__( 'icon/image', 'deep' ),
			'type'			=> 'colorpicker',
			'heading'		=> esc_html__('Icon color (leave bank for default color)', 'deep'),
			'param_name'	=> 'icon_color',
			'value'			=> '',
			'description'	=> esc_html__( 'Select icon color', 'deep'),
			'dependency'	=> array(
				'element'	=> 'icon_color_type',
				'value'		=> 'icon-solid-color',
			),
		),
		array(
			'group'				=> esc_html__( 'icon/image', 'deep' ),
			'type'				=> 'colorpicker',
			'heading'			=> esc_html__('color 1', 'deep'),
			'param_name'		=> 'icon_grad_color_1',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
			'dependency'		=> array(
				'element'	=> 'icon_color_type',
				'value'		=> 'icon_gradient',
			),
		),
		array(
			'group'				=> esc_html__( 'icon/image', 'deep' ),
			'type'				=> 'colorpicker',
			'heading'			=> esc_html__('color 2', 'deep'),
			'param_name'		=> 'icon_grad_color_2',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
			'dependency'		=> array(
				'element'	=> 'icon_color_type',
				'value'		=> 'icon_gradient',
			),
		),
		array(
			'group'				=> esc_html__( 'icon/image', 'deep' ),
			'type'				=> 'colorpicker',
			'heading'			=> esc_html__('color 3', 'deep'),
			'param_name'		=> 'icon_grad_color_3',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
			'dependency'		=> array(
				'element'	=> 'icon_color_type',
				'value'		=> 'icon_gradient',
			),
		),
		array(
			'group'				=> esc_html__( 'icon/image', 'deep' ),
			'type'				=> 'colorpicker',
			'heading'			=> esc_html__('color 4', 'deep'),
			'param_name'		=> 'icon_grad_color_4',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
			'dependency'		=> array(
				'element'	=> 'icon_color_type',
				'value'		=> 'icon_gradient',
			),
		),
		array(
			'group'			=> esc_html__( 'icon/image', 'deep' ),
			'type'			=> 'textfield',
			'heading'		=> esc_html__( 'Direction', 'deep' ),
			'param_name'	=> 'icon_grad_direction',
			'value'			=> '',
			'description'	=> esc_html__( 'Gradient direction example: 70', 'deep'),
			'dependency'	=> array(
				'element'	=> 'icon_color_type',
				'value'		=> 'icon_gradient',
			),
		),




		array(
			'group'				=> esc_html__( 'icon/image', 'deep' ),
			'type'				=> 'dropdown',
			'heading'			=> esc_html__( 'Hover Color type', 'deep' ),
			'param_name'		=> 'icon_color_type_hover',
			'value'				=> array(
				'Solid color'	=> 'icon-solid-color_hover',
				'Gradient'		=> 'icon_gradient_hover',
			),
			'std'				=> 'icon-solid-color_hover'
		),
		array(
			'group'			=> esc_html__( 'icon/image', 'deep' ),
			'type'			=> 'colorpicker',
			'heading'		=> esc_html__('Hover Icon color (leave bank for default color)', 'deep'),
			'param_name'	=> 'icon_color_hover',
			'value'			=> '',
			'description'	=> esc_html__( 'Select icon color', 'deep'),
			'dependency'	=> array(
				'element'	=> 'icon_color_type_hover',
				'value'		=> 'icon-solid-color_hover',
			),
		),
		array(
			'group'				=> esc_html__( 'icon/image', 'deep' ),
			'type'				=> 'colorpicker',
			'heading'			=> esc_html__('color 1', 'deep'),
			'param_name'		=> 'icon_grad_color_1_hover',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
			'dependency'		=> array(
				'element'	=> 'icon_color_type_hover',
				'value'		=> 'icon_gradient_hover',
			),
		),
		array(
			'group'				=> esc_html__( 'icon/image', 'deep' ),
			'type'				=> 'colorpicker',
			'heading'			=> esc_html__('color 2', 'deep'),
			'param_name'		=> 'icon_grad_color_2_hover',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
			'dependency'		=> array(
				'element'	=> 'icon_color_type_hover',
				'value'		=> 'icon_gradient_hover',
			),
		),
		array(
			'group'				=> esc_html__( 'icon/image', 'deep' ),
			'type'				=> 'colorpicker',
			'heading'			=> esc_html__('color 3', 'deep'),
			'param_name'		=> 'icon_grad_color_3_hover',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
			'dependency'		=> array(
				'element'	=> 'icon_color_type_hover',
				'value'		=> 'icon_gradient_hover',
			),
		),
		array(
			'group'				=> esc_html__( 'icon/image', 'deep' ),
			'type'				=> 'colorpicker',
			'heading'			=> esc_html__('color 4', 'deep'),
			'param_name'		=> 'icon_grad_color_4_hover',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
			'dependency'		=> array(
				'element'	=> 'icon_color_type_hover',
				'value'		=> 'icon_gradient_hover',
			),
		),
		array(
			'group'			=> esc_html__( 'icon/image', 'deep' ),
			'type'			=> 'textfield',
			'heading'		=> esc_html__( 'Direction', 'deep' ),
			'param_name'	=> 'icon_grad_direction_hover',
			'value'			=> '',
			'description'	=> esc_html__( 'Gradient direction example: 70', 'deep'),
			'dependency'	=> array(
				'element'	=> 'icon_color_type_hover',
				'value'		=> 'icon_gradient_hover',
			),
		),


		// icon/image Border
		array(
			'group'			=> esc_html__( 'icon/image', 'deep' ),
			'type'			=> 'dropdown',
			'heading'		=> esc_html__( 'Border', 'deep' ),
			'param_name'	=> 'icon_border',
			'value'			=> array(
				'none'		=> 'none',		
				'dotted'	=> 'dotted',		
				'dashed'	=> 'dashed',		
				'solid'		=> 'solid',		
				'double'	=> 'double',		
				'groove'	=> 'groove',		
				'ridge'		=> 'ridge',		
				'inset'		=> 'inset',		
				'outset'	=> 'outset',		
			),
		),
		array(
			'group'				=> 'icon/image',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('border top', 'deep'),
			'param_name'		=> 'icon_border_bord_top',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element'	=> 'icon_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),
		array(
			'group'				=> 'icon/image',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('border right', 'deep'),
			'param_name'		=> 'icon_border_bord_right',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element'	=> 'icon_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),
		array(
			'group'				=> 'icon/image',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('border bottom', 'deep'),
			'param_name'		=> 'icon_border_bord_bottom',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element'	=> 'icon_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),
		array(
			'group'				=> 'icon/image',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('border left', 'deep'),
			'param_name'		=> 'icon_border_bord_left',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element'	=> 'icon_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),
		array(
			'group'				=> 'icon/image',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('border top left radius', 'deep'),
			'param_name'		=> 'icon_border_bord_top_left_radius',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element'	=> 'icon_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),
		array(
			'group'				=> 'icon/image',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('border top right radius', 'deep'),
			'param_name'		=> 'icon_border_bord_top_right_radius',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element'	=> 'icon_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),
		array(
			'group'				=> 'icon/image',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('border bottom left radius', 'deep'),
			'param_name'		=> 'icon_border_bord_bottom_left_radius',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element'	=> 'icon_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),
		array(
			'group'				=> 'icon/image',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('border bottom right radius', 'deep'),
			'param_name'		=> 'icon_border_bord_bottom_right_radius',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
			'dependency'	=> array(
				'element'	=> 'icon_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),
		array(
			'group'			=> 'icon/image',
			'type'			=> 'colorpicker',
			'heading'		=> esc_html__('Border color', 'deep'),
			'param_name'	=> 'icon_border_border_color',
			'value'			=> '',
			'description'	=> esc_html__( 'Select border color (leave blank for default color)', 'deep'),
			'dependency'	=> array(
				'element'	=> 'icon_border',
				'value'		=> array( 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', ),
			),
		),


		array(
			'group'				=> 'icon/image',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Padding top', 'deep'),
			'param_name'		=> 'icon_pad_top',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
		),
		array(
			'group'				=> 'icon/image',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Padding right', 'deep'),
			'param_name'		=> 'icon_pad_right',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
		),
		array(
			'group'				=> 'icon/image',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Padding bottom', 'deep'),
			'param_name'		=> 'icon_pad_bottom',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
		),
		array(
			'group'				=> 'icon/image',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Padding left', 'deep'),
			'param_name'		=> 'icon_pad_left',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
		),
		array(
			'group'				=> 'icon/image',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Margin top', 'deep'),
			'param_name'		=> 'icon_marg_top',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
		),
		array(
			'group'				=> 'icon/image',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Margin right', 'deep'),
			'param_name'		=> 'icon_marg_right',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
		),
		array(
			'group'				=> 'icon/image',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Margin bottom', 'deep'),
			'param_name'		=> 'icon_marg_bottom',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
		),
		array(
			'group'				=> 'icon/image',
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Margin left', 'deep'),
			'param_name'		=> 'icon_marg_left',
			'value'				=> '',
			'edit_field_class'	=> 'vc_col-sm-3 wn-px',
		),
		array(
			'group'			=> 'icon/image',
			'type'			=> 'radio',
			'heading'		=> esc_html__('Alignment', 'deep'),
			'param_name'	=> 'icon_align',
			'value'			=> '',
			'options'		=> array(
				'left'		=> 'left',
				'center'	=> 'center',
				'right'		=> 'right',
			),
		),
		array(
			'group'			=> 'icon/image',
			'type'			=> 'iconfonts',
			'heading' 		=> esc_html__( 'Pick an icon', 'deep' ),
			'param_name'	=> 'icon_name',
			'value'			=> '',
			'description'	=> esc_html__( 'Select Icon', 'deep'),
			'dependency'	=> array( 'element' => 'icon_or_image', 'value' => 'icon' ),
		),

		// box shadow
		array(
			'group'			=> 'Box shadow',
			'type'			=> 'textfield',
			'heading'		=> esc_html__( 'X offset', 'deep' ),
			'param_name'	=> 'shadow_left',
			'value'			=> '',
			'edit_field_class'	=> 'vc_col-sm-6 vc_column paddingtop wn-px',
		),
		array(
			'group'			=> 'Box shadow',
			'type'			=> 'textfield',
			'heading'		=> esc_html__( 'Y offset', 'deep' ),
			'param_name'	=> 'shadow_top',
			'value'			=> '',
			'edit_field_class'	=> 'vc_col-sm-6 vc_column wn-px',
		),
		array(
			'group'			=> 'Box shadow',
			'type'			=> 'textfield',
			'heading'		=> esc_html__( 'Blur', 'deep' ),
			'param_name'	=> 'shadow_blur',
			'value'			=> '',
			'edit_field_class'	=> 'vc_col-sm-6 vc_column paddingtop wn-px',
		),
		array(
			'group'			=> 'Box shadow',
			'type'			=> 'textfield',
			'heading'		=> esc_html__( 'Spread', 'deep' ),
			'param_name'	=> 'shadow_spread',
			'value'			=> '',
			'edit_field_class'	=> 'vc_col-sm-6 vc_column paddingtop wn-px',
		),
		array(
			'group'			=> 'Box shadow',
			'type'			=> 'dropdown',
			'heading'		=> esc_html__( 'Shadow Status', 'deep' ),
			'param_name'	=> 'shadow_status',
			'value'			=> array(
				'Outset'	=> '',		
				'Inset'	=> 'inset',		
			),
			'edit_field_class'	=> 'vc_col-sm-6 vc_column paddingtop paddingbottom',
		),
		array(
			'group'			=> 'Box shadow',
			'type'			=> 'colorpicker',
			'heading'		=> esc_html__( 'Shadow color', 'deep' ),
			'param_name'	=> 'shadow_color',
			'value'			=> '',
			'edit_field_class'	=> 'vc_col-sm-6 vc_column paddingtop paddingbottom',
		),

		// Class & ID 
		array(
			'group'			=> 'Class & ID',
			'type'			=> 'textfield',
			'heading'		=> esc_html__( 'Extra Class', 'deep' ),
			'param_name'	=> 'shortcodeclass',
			'value'			=> '',
			'edit_field_class'	=> 'vc_col-sm-6 vc_column paddingtop',
		),
		array(
			'group'			=> 'Class & ID',
			'type'			=> 'textfield',
			'heading'		=> esc_html__( 'ID', 'deep' ),
			'param_name'	=> 'shortcodeid',
			'value'			=> '',
			'edit_field_class'	=> 'vc_col-sm-6 vc_column paddingtop',
		),
	),

) );


?>