<?php
vc_map( array(
	"name"			=>"Button",
	"base"			=> "button",
	"description"	=> "Button shortcode",
	"category"		=> esc_html__( 'Webnus Shortcodes', 'deep' ),
	"icon"			=> "webnus-button",
	"params"		=> array(
		array(
			"type"			=> "dropdown",
			"heading"		=> esc_html__( "Shape", 'deep' ),
			"param_name"	=> "shape",
			"value"			=> array(
				"Default"	=>"",
				"Square"	=>"square",
				"Rounded"	=>"rounded",
			),
			"description" 	=> esc_html__( "Button Type", 'deep')
		),
		
		array(
			"type"			=> "textfield",
			"heading"		=> esc_html__( "Button text", 'deep' ),
			"param_name"	=> "btn_content",
			"value"			=>'',
			"description"	=> esc_html__( "Button Text Button text", 'deep'),
			'admin_label'   => true,
		),
		array(
			'group'			=> esc_html__( 'Styling', 'deep' ),
			'type'			=> 'checkbox',
			'heading'		=> esc_html__( 'Use theme default font family?', 'deep' ),
			'param_name'	=> 'btn_theme_fonts',
			'value'			=> array( esc_html__( 'Yes', 'deep' ) => 'yes' ),
			'description'	=> esc_html__( 'Use font family from the theme.', 'deep' ),
			'std'			=> 'yes',
		),
		array(
			'group'			=> esc_html__( 'Styling', 'deep' ),
			'type'			=> 'google_fonts',
			'param_name'	=> 'btn_text_font',
			'value'			=> '',
			'settings'		=> array(
				'fields'	=> array(
					'font_family_description' => esc_html__( 'Select font family.', 'deep' ),
					'font_style_description'  => esc_html__( 'Select styling.', 'deep' ),
				),
			),
			'dependency'	=> array(
				'element'				=> 'btn_theme_fonts',
				'value_not_equal_to'	=> 'yes',
			),
		),
		array(
			'group'				=> 'Styling',
			'type'				=> 'dropdown',
			'heading'			=> esc_html__( 'Button Skin', 'deep' ),
			'param_name'		=> 'botton_skin',
			'value'				=> array(
				'Predefined'	=> 'predefined',
				'Custom'		=> 'custom',
			),
			'description'	=> esc_html__( 'Select shortcode type', 'deep'),
		),
		array(
			'group'				=> 'Styling',
			"type"			=> "dropdown",
			"heading"		=> esc_html__( "Color", 'deep' ),
			"param_name"	=> "color",
			"description"	=> esc_html__( "Button Color", 'deep'),
			"value"			=> array(
				"Default"	=>"theme-skin",
				"Green"		=>"green",
				"Gold"		=>"gold",
				"Red"		=>"red",
				"Blue"		=>"blue",
				"Gray"		=>"gray",
				"Dark gray"	=>"dark-gray",
				"Cherry"	=>"cherry",
				"Orchid"	=>"orchid",
				"Pink"		=>"pink",
				"Orange"	=>"orange",
				"Teal"		=>"teal",
				"SkyBlue"	=>"skyblue",
				"Jade"		=>"jade",
				"White"		=>"white",
				"Black"		=>"black",
			),
			'dependency'	=> array( 'element' => 'botton_skin', 'value' => 'predefined' ),
		),
		array(
			'group'				=> 'Styling',
			'type'				=> 'textfield',
			'heading'			=> esc_html__( 'font Size', 'deep' ),
			'param_name'		=> 'btn_font_size',
			'value'				=> '',
			'description'		=> esc_html__( 'Please enter desired value with px', 'deep'),
			'edit_field_class'	=> 'vc_col-sm-4 vc_column paddingtop paddingbottom',
		),
		array(
			'group'				=> 'Styling',
			'type'				=> 'textfield',
			'heading'			=> esc_html__( 'Letter Spacing', 'deep' ),
			'param_name'		=> 'btn_letterspacing',
			'value'				=> '',
			'description'		=> esc_html__( 'Please enter desired value with px', 'deep'),
			'edit_field_class'	=> 'vc_col-sm-4 vc_column paddingtop paddingbottom',
		),
		array(
			'group'				=> 'Styling',
			'type'				=> 'textfield',
			'heading'			=> esc_html__( 'Font Weight', 'deep' ),
			'param_name'		=> 'btn_fontweight',
			'value'				=> '',
			'description'		=> esc_html__( 'Please enter desired value without px (Example:700)', 'deep'),
			'edit_field_class'	=> 'vc_col-sm-4 vc_column paddingtop paddingbottom',
		),
		array(
			'group'				=> 'Styling',
			'type'				=> 'textfield',
			'heading'			=> esc_html__( 'Padding Top', 'deep' ),
			'param_name'		=> 'btn_pad_top',
			'value'				=> '',
			'description'		=> esc_html__( 'Please enter desired value with px', 'deep'),
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
		),
		array(
			'group'				=> 'Styling',
			'type'				=> 'textfield',
			'heading'			=> esc_html__( 'Padding Right', 'deep' ),
			'param_name'		=> 'btn_pad_right',
			'value'				=> '',
			'description'		=> esc_html__( 'Please enter desired value with px', 'deep'),
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
		),
		array(
			'group'				=> 'Styling',
			'type'				=> 'textfield',
			'heading'			=> esc_html__( 'Padding Bottom', 'deep' ),
			'param_name'		=> 'btn_pad_bottom',
			'value'				=> '',
			'description'		=> esc_html__( 'Please enter desired value with px', 'deep'),
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
		),
		array(
			'group'				=> 'Styling',
			'type'				=> 'textfield',
			'heading'			=> esc_html__( 'Padding Left', 'deep' ),
			'param_name'		=> 'btn_pad_left',
			'value'				=> '',
			'description'		=> esc_html__( 'Please enter desired value with px', 'deep'),
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
		),
		array(
			'group'				=> 'Styling',
			'type'				=> 'textfield',
			'heading'			=> esc_html__( 'margin Top', 'deep' ),
			'param_name'		=> 'btn_marg_top',
			'value'				=> '',
			'description'		=> esc_html__( 'Please enter desired value with px', 'deep'),
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
		),
		array(
			'group'				=> 'Styling',
			'type'				=> 'textfield',
			'heading'			=> esc_html__( 'margin Right', 'deep' ),
			'param_name'		=> 'btn_marg_right',
			'value'				=> '',
			'description'		=> esc_html__( 'Please enter desired value with px', 'deep'),
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
		),
		array(
			'group'				=> 'Styling',
			'type'				=> 'textfield',
			'heading'			=> esc_html__( 'margin Bottom', 'deep' ),
			'param_name'		=> 'btn_marg_bottom',
			'value'				=> '',
			'description'		=> esc_html__( 'Please enter desired value with px', 'deep'),
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
		),
		array(
			'group'				=> 'Styling',
			'type'				=> 'textfield',
			'heading'			=> esc_html__( 'margin Left', 'deep' ),
			'param_name'		=> 'btn_marg_left',
			'value'				=> '',
			'description'		=> esc_html__( 'Please enter desired value with px', 'deep'),
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
		),

		array(
			'group'				=> 'Styling',
			'type'				=> 'textfield',
			'heading'			=> esc_html__( 'Border Width Top', 'deep' ),
			'param_name'		=> 'btn_border_width_top',
			'value'				=> '',
			'description'		=> esc_html__( 'Please enter desired value with px', 'deep'),
			'dependency'	=> array( 'element' => 'botton_skin', 'value' => 'custom' ),			
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
		),

		array(
			'group'				=> 'Styling',
			'type'				=> 'textfield',
			'heading'			=> esc_html__( 'Border Width Right', 'deep' ),
			'param_name'		=> 'btn_border_width_right',
			'value'				=> '',
			'description'		=> esc_html__( 'Please enter desired value with px', 'deep'),
			'dependency'	=> array( 'element' => 'botton_skin', 'value' => 'custom' ),			
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
		),
		
		array(
			'group'				=> 'Styling',
			'type'				=> 'textfield',
			'heading'			=> esc_html__( 'Border Width Bottom', 'deep' ),
			'param_name'		=> 'btn_border_width_bottom',
			'value'				=> '',
			'description'		=> esc_html__( 'Please enter desired value with px', 'deep'),
			'dependency'	=> array( 'element' => 'botton_skin', 'value' => 'custom' ),			
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
		),

		array(
			'group'				=> 'Styling',
			'type'				=> 'textfield',
			'heading'			=> esc_html__( 'Border Width Left', 'deep' ),
			'param_name'		=> 'btn_border_width_left',
			'value'				=> '',
			'description'		=> esc_html__( 'Please enter desired value with px', 'deep'),
			'dependency'	=> array( 'element' => 'botton_skin', 'value' => 'custom' ),			
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
		),

		array(
			'group'				=> 'Styling',
			'type'				=> 'textfield',
			'heading'			=> esc_html__( 'Border Radius Top', 'deep' ),
			'param_name'		=> 'btn_border_radius_top',
			'value'				=> '',
			'description'		=> esc_html__( 'Please enter desired value with px', 'deep'),
			'dependency'	=> array( 'element' => 'botton_skin', 'value' => 'custom' ),			
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
		),

		array(
			'group'				=> 'Styling',
			'type'				=> 'textfield',
			'heading'			=> esc_html__( 'Border Radius Right', 'deep' ),
			'param_name'		=> 'btn_border_radius_right',
			'value'				=> '',
			'description'		=> esc_html__( 'Please enter desired value with px', 'deep'),
			'dependency'	=> array( 'element' => 'botton_skin', 'value' => 'custom' ),			
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
		),

		array(
			'group'				=> 'Styling',
			'type'				=> 'textfield',
			'heading'			=> esc_html__( 'Border Radius Bottom', 'deep' ),
			'param_name'		=> 'btn_border_radius_bottom',
			'value'				=> '',
			'description'		=> esc_html__( 'Please enter desired value with px', 'deep'),
			'dependency'	=> array( 'element' => 'botton_skin', 'value' => 'custom' ),			
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
		),

		array(
			'group'				=> 'Styling',
			'type'				=> 'textfield',
			'heading'			=> esc_html__( 'Border Radius Left', 'deep' ),
			'param_name'		=> 'btn_border_radius_left',
			'value'				=> '',
			'description'		=> esc_html__( 'Please enter desired value with px', 'deep'),
			'dependency'	=> array( 'element' => 'botton_skin', 'value' => 'custom' ),			
			'edit_field_class'	=> 'vc_col-sm-3 vc_column paddingtop paddingbottom',
		),

		array(
			'group'				=> 'Styling',
			'type'			=> 'colorpicker',
			'heading'		=> esc_html__('Button color', 'deep'),
			'param_name'	=> 'btn_color',
			'value'			=> '',
			'description'	=> esc_html__( 'Select Button color (leave blank for default color)', 'deep'),
			'dependency'	=> array( 'element' => 'botton_skin', 'value' => 'custom' ),
			'edit_field_class'	=> 'vc_col-sm-6 vc_column paddingbottom',
		),
		array(
			'group'				=> 'Styling',
			'type'			=> 'colorpicker',
			'heading'		=> esc_html__('Button color Hover', 'deep'),
			'param_name'	=> 'btn_color_hover',
			'value'			=> '',
			'description'	=> esc_html__( 'Select Button color Hover (leave blank for default color)', 'deep'),
			'dependency'	=> array( 'element' => 'botton_skin', 'value' => 'custom' ),
			'edit_field_class'	=> 'vc_col-sm-6 vc_column paddingbottom',
		),
		array(
			'group'			=> 'Styling',
			'type'			=> 'colorpicker',
			'heading'		=> esc_html__('Button Border color', 'deep'),
			'param_name'	=> 'btn_border_color',
			'value'			=> '',
			'description'	=> esc_html__( 'select button border color (leave blank for default color)', 'deep'),
			'dependency'	=> array( 'element' => 'botton_skin', 'value' => 'custom' ),
			'edit_field_class'	=> 'vc_col-sm-6 vc_column paddingbottom',
		),
		array(
			'group'			=> 'Styling',
			'type'			=> 'colorpicker',
			'heading'		=> esc_html__('Button Border color Hover', 'deep'),
			'param_name'	=> 'btn_border_color_hover',
			'value'			=> '',
			'description'	=> esc_html__( 'select button border color hover (leave blank for default color)', 'deep'),
			'dependency'	=> array( 'element' => 'botton_skin', 'value' => 'custom' ),
			'edit_field_class'	=> 'vc_col-sm-6 vc_column paddingbottom',
		),
		array(
			'group'				=> 'Styling',
			'type'			=> 'colorpicker',
			'heading'		=> esc_html__('Button background 1', 'deep'),
			'param_name'	=> 'btn_background',
			'value'			=> '',
			'description'	=> esc_html__( 'Select Button background (leave blank for default color)', 'deep'),
			'dependency'	=> array( 'element' => 'botton_skin', 'value' => 'custom' ),
			'edit_field_class'	=> 'vc_col-sm-4 vc_column paddingbottom',
		),
		array(
			'group'				=> 'Styling',
			'type'			=> 'colorpicker',
			'heading'		=> esc_html__('Button background 2', 'deep'),
			'param_name'	=> 'btn_background_1',
			'value'			=> '',
			'description'	=> esc_html__( 'Select Button background (leave blank for default color)', 'deep'),
			'dependency'	=> array( 'element' => 'botton_skin', 'value' => 'custom' ),
			'edit_field_class'	=> 'vc_col-sm-4 vc_column paddingbottom',
		),
		array(
			'group'				=> 'Styling',
			'type'			=> 'colorpicker',
			'heading'		=> esc_html__('Button background 3', 'deep'),
			'param_name'	=> 'btn_background_2',
			'value'			=> '',
			'description'	=> esc_html__( 'Select Button background (leave blank for default color)', 'deep'),
			'dependency'	=> array( 'element' => 'botton_skin', 'value' => 'custom' ),
			'edit_field_class'	=> 'vc_col-sm-4 vc_column paddingbottom',
		),
		array(
			'group'			=> 'Styling',
			'type'			=> 'colorpicker',
			'heading'		=> esc_html__('Button background Hover 1', 'deep'),
			'param_name'	=> 'btn_background_hover',
			'value'			=> '',
			'description'	=> esc_html__( 'Select Button background 1 (leave blank for default color)', 'deep'),
			'dependency'	=> array( 'element' => 'botton_skin', 'value' => 'custom' ),
			'edit_field_class'	=> 'vc_col-sm-4 vc_column paddingbottom',
		),
		array(
			'group'			=> 'Styling',
			'type'			=> 'colorpicker',
			'heading'		=> esc_html__('Button background Hover 2', 'deep'),
			'param_name'	=> 'btn_background_hover_1',
			'value'			=> '',
			'description'	=> esc_html__( 'Select Button background 2 (leave blank for default color)', 'deep'),
			'dependency'	=> array( 'element' => 'botton_skin', 'value' => 'custom' ),
			'edit_field_class'	=> 'vc_col-sm-4 vc_column paddingbottom',
		),
		array(
			'group'			=> 'Styling',
			'type'			=> 'colorpicker',
			'heading'		=> esc_html__('Button background Hover 3', 'deep'),
			'param_name'	=> 'btn_background_hover_2',
			'value'			=> '',
			'description'	=> esc_html__( 'Select Button background 3 (leave blank for default color)', 'deep'),
			'dependency'	=> array( 'element' => 'botton_skin', 'value' => 'custom' ),
			'edit_field_class'	=> 'vc_col-sm-4 vc_column paddingbottom',
		),
		array(
			'group'			=> 'Styling',
			'type'			=> 'textfield',
			'heading'		=> esc_html__( 'Direction', 'deep' ),
			'param_name'	=> 'bg_grad_direction',
			'value'			=> '',
			'description'	=> esc_html__( 'Gradient direction example: 70deg', 'deep'),
			'dependency'	=> array( 'element' => 'botton_skin', 'value' => 'custom' ),
			'edit_field_class'	=> 'vc_col-sm-6 vc_column paddingbottom',
		),
		array(
			'group'			=> 'Styling',
			'type'			=> 'textfield',
			'heading'		=> esc_html__( 'Hover Direction', 'deep' ),
			'param_name'	=> 'bg_hover_grad_direction',
			'value'			=> '',
			'description'	=> esc_html__( 'Gradient direction example: 70deg', 'deep'),
			'dependency'	=> array( 'element' => 'botton_skin', 'value' => 'custom' ),
			'edit_field_class'	=> 'vc_col-sm-6 vc_column paddingbottom',
		),
		array(
			'group'			=> 'Styling',
			'type'			=> 'checkbox',
			'heading'		=> esc_html__( 'Do you want to have arrow when hover?' , 'deep' ),
			'description'	=> esc_html__( 'Put the arrow for button when hovering over it.' , 'deep'),
			'param_name'	=> 'button_arrow',
			'value'			=> array( 
				esc_html__( 'Enable' , 'deep') => 'enable'
			),
			'dependency'	=> array( 'element' => 'botton_skin', 'value' => 'custom' ),
			'edit_field_class'	=> 'vc_col-sm-12 vc_column paddingbottom',
		),
		array(
			"type"			=> "textfield",
			"heading"		=> esc_html__( "Button link", 'deep' ),
			"param_name"	=> "url",
			"value"			=>'#',
			"description"	=> esc_html__( "Button Button link Link", 'deep')
		),
					
		array(
			'type'			=> 'dropdown',
			'heading'		=> esc_html__( 'Target', 'deep' ),
			'param_name'	=> 'target',
			'description'	=> esc_html__( 'Button Link Target ( set "blank" to open the link in a new tab', 'deep'),
			'value'			=> array(
				'Parent'	=>'_parent',
				'Self'		=>'_self',
				'Blank'		=>'_blank',
				'Top'		=>'_top',
			),
		),
								
		array(
			"type"			=> "dropdown",
			"heading"		=> esc_html__( "Size", 'deep' ),
			"param_name"	=> "size",
			"description"	=> esc_html__( "Button Size", 'deep'),
			"value"			=> array(
				"Small"		=>"small",
				"Medium"	=>"medium",
				"Large"		=>"large",	
			),
		),

		array(
			"type"			=> "dropdown",
			"heading"		=> esc_html__( "Set bordered style", 'deep' ),
			"param_name"	=> "border",
			"value"			=>array('Normal'=>'false','Bordered'=>'true'),
			'edit_field_class'	=> 'vc_col-sm-12 vc_column paddingtop paddingbottom',
		),

		array(
			'group'			=> 'Icon',
			'type'			=> 'colorpicker',
			'heading'		=> esc_html__('Button Icon color', 'deep'),
			'param_name'	=> 'btn_icon_color',
			'value'			=> '',
			'edit_field_class'	=> 'vc_col-sm-6 vc_column paddingbottom',
		),		

		array(
			'group'			=> 'Icon',
			'type'			=> 'colorpicker',
			'heading'		=> esc_html__('Button Hover Icon color', 'deep'),
			'param_name'	=> 'btn_icon_color_hover',
			'value'			=> '',
			'edit_field_class'	=> 'vc_col-sm-6 vc_column paddingbottom',
		),		

		array(
			'group'			=> 'Icon',
			"type"			=> "iconfonts",
			"heading"		=> esc_html__( "Icon", 'deep' ),
			"param_name"	=> "icon",
			"value"			=>'',
			"description"	=> esc_html__( "Select Button Icon", 'deep')
		),

		array(
			'group'			=> 'box shadow',
			'type'			=> 'textfield',
			'heading'		=> esc_html__( 'X offset', 'deep' ),
			'param_name'	=> 'shadow_left',
			'value'			=> '',
			'description'	=> esc_html__( 'Please enter desired value with px', 'deep'),
			'edit_field_class'	=> 'vc_col-sm-6 vc_column paddingtop',
		),
		array(
			'group'			=> 'box shadow',
			'type'			=> 'textfield',
			'heading'		=> esc_html__( 'Y offset', 'deep' ),
			'param_name'	=> 'shadow_top',
			'value'			=> '',
			'description'	=> esc_html__( 'Please enter desired value with px', 'deep'),
			'edit_field_class'	=> 'vc_col-sm-6 vc_column',
		),
		array(
			'group'			=> 'box shadow',
			'type'			=> 'textfield',
			'heading'		=> esc_html__( 'Blur', 'deep' ),
			'param_name'	=> 'shadow_blur',
			'value'			=> '',
			'description'	=> esc_html__( 'Please enter desired value with px', 'deep'),
			'edit_field_class'	=> 'vc_col-sm-6 vc_column paddingtop',
		),
		array(
			'group'			=> 'box shadow',
			'type'			=> 'textfield',
			'heading'		=> esc_html__( 'Spread', 'deep' ),
			'param_name'	=> 'shadow_spread',
			'value'			=> '',
			'description'	=> esc_html__( 'Please enter desired value with px', 'deep'),
			'edit_field_class'	=> 'vc_col-sm-6 vc_column paddingtop',
		),
		array(
			'group'			=> 'box shadow',
			'type'			=> 'dropdown',
			'heading'		=> esc_html__( 'Shadow Status', 'deep' ),
			'param_name'	=> 'shadow_status',
			'value'			=> array(
				'Outset'	=> '',		
				'Inset'	=> 'inset',		
			),
			'edit_field_class'	=> 'vc_col-sm-6 vc_column paddingtop paddingbottom',
		),
		array(
			'group'			=> 'box shadow',
			'type'			=> 'colorpicker',
			'heading'		=> esc_html__( 'Shadow color', 'deep' ),
			'param_name'	=> 'shadow_color',
			'value'			=> '',
			'edit_field_class'	=> 'vc_col-sm-6 vc_column paddingtop paddingbottom',
		),
		// Class & ID 
		array(
			'group'			=> 'Class & ID',
			'type'			=> 'textfield',
			'heading'		=> esc_html__( 'Extra Class', 'deep' ),
			'param_name'	=> 'shortcodeclass',
			'value'			=> '',
			'edit_field_class'	=> 'vc_col-sm-6 vc_column paddingtop',
		),
		array(
			'group'			=> 'Class & ID',
			'type'			=> 'textfield',
			'heading'		=> esc_html__( 'ID', 'deep' ),
			'param_name'	=> 'shortcodeid',
			'value'			=> '',
			'edit_field_class'	=> 'vc_col-sm-6 vc_column paddingtop',
		),
		
	),
));
?>