<?php
if ( ! function_exists( 'deep_kses' )) {
	function deep_kses() {
		return array(
			'a' => array(
				'href' => array(),
				'title' => array(),
				'target' => array(),
				'style' => array(),
				'class' => array(),
			),
			'br' => array(),
			'em' => array(),
			'strong' => array(),
			'span' => array(
				'class' => array(),
			),
		);
	}
}
vc_map( array(
        'name'      => 'Testimonial Slider',
        'base'      => 'testimonial_slider',
        'category'  =>  esc_html__( 'Webnus Shortcodes' , 'deep' ),
        'icon'      => 'webnus-testimonialslider',
        'params'    => array(
                array(
                    'type'          => 'dropdown',
                    'heading'       => esc_html__( 'Type' , 'deep' ),
                    'description'   => wp_kses( __( 'You can choose from these pre-designed types. <a href="http://deeptem.com/features/carousels/testimonial-slider/" target="_blank">View All Types</a>', 'deep'), deep_kses() ),
                    'param_name'    => 'type',
                    'value'         => array(
                        'One'     =>'mono',
                        'Two'     =>'di',
                        'Three'   =>'tri',
                        'Four'    =>'tetra',
                        'Five'    =>'penta',
                        'Six'     =>'hexa', 
                        'Seven'   =>'hepta',
                        'Eight'   =>'octa', 
                        'Nine'    =>'nona',
                        'Ten'     =>'deca',
                        'Eleven'  =>'undeca',
                        'twelve'  =>'dodeca',
                    )
                ),
                array(
                    'type'          => 'attach_image',
                    'heading'       => esc_html__( 'Background Image', 'deep' ),
                    'param_name'    => 'testimonial_img_octa',
                    'description'   => esc_html__( 'Testimonial Image', 'deep'),
                    'dependency'    => array(
                        'element'   => 'type',
                        'value'     => array('octa'),
                    )
                ),
                array(
                    'type'          => 'textfield',
                    'heading'       => esc_html__( 'Image Size', 'deep' ),
                    'param_name'    => 'thumbnail',
                    'value'         => '',
                    'description'   => esc_html__( 'Enter image size (Example: 100x100 (Width x Height)).', 'deep'),
                    'dependency'    => array(
                        'element'   => 'type',
                        'value'     => array( 'mono', 'di', 'tri', 'tetra', 'penta', 'hexa', 'hepta', 'deca' ),
                    ),
                ),
                array(
                    'type'          => 'colorpicker',
                    'heading'       => esc_html__('Background Color', 'deep'),
                    'param_name'    => 'testimonial_bgcolor',
                    'value'         => '',
                    'description'   => esc_html__('Select Background Color', 'deep'),
                    'dependency'    => array(
                        'element'   => 'type',
                        'value'     => 'octa',
                    ),
                ),
                array(
                    'heading'       => esc_html__( 'Testimonial Item' , 'deep' ),
                    'description'   => esc_html__( 'Please Add Item' , '' ),
                    'dependency'    => array(
                        'element'   => 'type',
                        'value'     => array( 'mono' , 'di' , 'tri' , 'tetra' , 'penta' , 'hexa' , 'hepta' , 'deca' ),
                    ),
                    'type'          => 'param_group',
                    'param_name'    => 'testimonial_item',
                    'params'        => array(
                        array(
                            'type'          => 'textfield',
                            'heading'       => esc_html__( 'Name', 'deep' ),
                            'param_name'    => 'testimonial_name',
                            'value'         =>'Name',
                            'description'   => esc_html__( 'Enter the Testimonial Name', 'deep'),
                        ),
                        array(
                            'type'          => 'attach_image',
                            'heading'       => esc_html__( 'Image', 'deep' ),
                            'param_name'    => 'testimonial_img_id',
                            'description'   => esc_html__( 'Testimonial Image', 'deep'),
                        ),
                        array(
                            'type'          => 'textfield',
                            'heading'       => esc_html__( 'Subtitle', 'deep' ),
                            'param_name'    => 'testimonial_subtitle',
                            'value'         =>'',
                            'description'   => esc_html__( 'Testimonial Subtitle', 'deep'),
                        ),
                        array(
                            'type'          => 'textarea',
                            'heading'       => esc_html__( 'Content', 'deep' ),
                            'param_name'    => 'testimonial_content',
                            'value'         => '',
                            'description'   => esc_html__( 'Enter the Testimonial content text', 'deep'),
                        ),
                        array(
                            'type'          => 'dropdown',
                            'heading'       => esc_html__( 'First Social Name', 'deep' ),
                            'param_name'    => 'testimonial_first_social',
                            'value'        => array(
                                "Twitter"       =>'twitter',
                                "Facebook"      =>'facebook',
                                "Google Plus"   =>'google-plus',
                                "Vimeo"         =>'vimeo',
                                "Dribbble"      =>'dribbble',
                                "Youtube"       =>'youtube',
                                "Pinterest"     =>'pinterest',
                                "LinkedIn"      =>'linkedin',
                                "Instagram"     =>'instagram',
                                ),
                                'std'           => 'twitter',
                            'description'       => esc_html__( 'Select Social Name', 'deep'),
                        ),
                        array(
                            'type'          => 'textfield',
                            'heading'       => esc_html__( 'First Social URL', 'deep' ),
                            'param_name'    => 'testimonial_first_url',
                            'value'         =>'',
                            'description'   => esc_html__( 'First social URL', 'deep'),
                        ),
                        array(
                            'type'          => 'dropdown',
                            'heading'       => esc_html__( 'Second Social Name', 'deep' ),
                            'param_name'    => 'testimonial_second_social',
                            'value'        => array(
                                "Twitter"       =>'twitter',
                                "Facebook"      =>'facebook',
                                "Google Plus"   =>'google-plus',
                                "Vimeo"         =>'vimeo',
                                "Dribbble"      =>'dribbble',
                                "Youtube"       =>'youtube',
                                "Pinterest"     =>'pinterest',
                                "LinkedIn"      =>'linkedin',
                                "Instagram"     =>'instagram',
                                ),
                                'std'           => 'facebook',
                            'description'       => esc_html__( 'Select Social Name', 'deep'),
                        ),
                        array(
                            'type'          => 'textfield',
                            'heading'       => esc_html__( 'Second Social URL', 'deep' ),
                            'param_name'    => 'testimonial_second_url',
                            'value'         =>'',
                            'description'   => esc_html__( 'Second social URL', 'deep'),
                        ),
                        array(
                            'type'          => 'dropdown',
                            'heading'       => esc_html__( 'Third Social Name', 'deep' ),
                            'param_name'    => 'testimonial_third_social',
                            'value'        => array(
                                "Twitter"       =>'twitter',
                                "Facebook"      =>'facebook',
                                "Google Plus"   =>'google-plus',
                                "Vimeo"         =>'vimeo',
                                "Dribbble"      =>'dribbble',
                                "Youtube"       =>'youtube',
                                "Pinterest"     =>'pinterest',
                                "LinkedIn"      =>'linkedin',
                                "Instagram"     =>'instagram',
                                ),
                                'std'           => 'google-plus',
                            'description'       => esc_html__( 'Select Social Name', 'deep'),
                        ),
                        array(
                            'type'          => 'textfield',
                            'heading'       => esc_html__( 'Third Social URL', 'deep' ),
                            'param_name'    => 'testimonial_third_url',
                            'value'         =>'',
                            'description'   => esc_html__( 'Third social URL', 'deep'),
                        ),
                        array(
                            'type'          => 'dropdown',
                            'heading'       => esc_html__( 'Fourth Social Name', 'deep' ),
                            'param_name'    => 'testimonial_fourth_social',
                            'value'         => array(
                                "Twitter"       =>'twitter',
                                "Facebook"      =>'facebook',
                                "Google Plus"   =>'google-plus',
                                "Vimeo"         =>'vimeo',
                                "Dribbble"      =>'dribbble',
                                "Youtube"       =>'youtube',
                                "Pinterest"     =>'pinterest',
                                "LinkedIn"      =>'linkedin',
                                "Instagram"     =>'instagram',
                                ),
                                'std'           => 'linkedin',
                            'description'       => esc_html__( 'Select Social Name', 'deep'),
                        ),
                        array(
                            'type'          => 'textfield',
                            'heading'       => esc_html__( 'Fourth Social URL', 'deep' ),
                            'param_name'    => 'testimonial_fourth_url',
                            'value'         =>'',
                            'description'   => esc_html__( 'Fourth social URL', 'deep'),
                        ),
                    )
                ), 
                array(
                    'heading'       => esc_html__( 'Testimonial Item' , 'deep' ),
                    'description'   => esc_html__( 'Please Add Item' , '' ),
                    'dependency'    => array( 'element' => 'type' , 'value' => 'octa'),
                    'type'          => 'param_group',
                    'param_name'    => 'testimonial_item_octa',
                    'params'        => array(
                        array(
                            'type'          => 'textfield',
                            'heading'       => esc_html__( 'Name', 'deep' ),
                            'param_name'    => 'testimonial_name_octa',
                            'value'         =>'Name',
                            'description'   => esc_html__( 'Enter the Testimonial Name', 'deep'),
                        ),
                        array(
                            'type'          => 'textfield',
                            'heading'       => esc_html__( 'Subtitle', 'deep' ),
                            'param_name'    => 'testimonial_subtitle_octa',
                            'value'         =>'',
                            'description'   => esc_html__( 'Testimonial Subtitle', 'deep'),
                        ),
                        array(
                            'type'          => 'textarea',
                            'heading'       => esc_html__( 'Content', 'deep' ),
                            'param_name'    => 'testimonial_content_octa',
                            'value'         => '',
                            'description'   => esc_html__( 'Enter the Testimonial content text', 'deep'),
                        ),
                    )
                ),
                array(
                    'heading'       => esc_html__( 'Testimonial Item' , 'deep' ),
                    'description'   => esc_html__( 'Please Add Item' , '' ),
                    'dependency'    => array( 
                        'element' => 'type', 
                        'value'   => array('nona','dodeca'),
                    ),
                    'type'          => 'param_group',
                    'param_name'    => 'testimonial_item_two',
                    'params'        => array(
                        array(
                            'type'          => 'textfield',
                            'heading'       => esc_html__( 'Name', 'deep' ),
                            'param_name'    => 'testimonial_name_two',
                            'value'         =>'Name',
                            'description'   => esc_html__( 'Enter the Testimonial Name', 'deep'),
                        ),
                        array(
                            'type'          => 'attach_image',
                            'heading'       => esc_html__( 'Image', 'deep' ),
                            'param_name'    => 'testimonial_img_id_two',
                            'description'   => esc_html__( 'Testimonial Image', 'deep'),
                        ),
                        array(
                            'type'          => 'textfield',
                            'heading'       => esc_html__( 'Title', 'deep' ),
                            'param_name'    => 'testimonial_title_two',
                            'value'         =>'',
                            'description'   => esc_html__( 'Testimonial title just show in type nine', 'deep'),
                        ),
                        array(
                            'type'          => 'textfield',
                            'heading'       => esc_html__( 'Subtitle', 'deep' ),
                            'param_name'    => 'testimonial_subtitle_two',
                            'value'         =>'',
                            'description'   => esc_html__( 'Testimonial Subtitle', 'deep'),
                        ),
                        array(
                            'type'          => 'textarea',
                            'heading'       => esc_html__( 'Content', 'deep' ),
                            'param_name'    => 'testimonial_content_two',
                            'value'         => '',
                            'description'   => esc_html__( 'Enter the Testimonial content text', 'deep'),
                        ),
                    )
                ),
                array(
                    'heading'       => esc_html__( 'Testimonial Items', 'deep' ),
                    'type'          => 'param_group',
                    'param_name'    => 'testimonial_item_eleven',
                    'dependency'    => array( 'element' => 'type' , 'value' => 'undeca'),
                    'params'            => array(
                        array(
                            'heading'       => esc_html__( 'Testimonial Content', 'deep' ),
                            'type'          => 'textarea',
                            'param_name'    => 'tc_content_t11',
                            'value'         => '',
                        ),
                        array(
                            'type' => 'dropdown',
                            'heading' => esc_html__( 'First Social Name', 'deep' ),
                            'param_name' => 'first_social',
                            'value' => array(
                                "Twitter"       =>'twitter',
                                "Facebook"      =>'facebook',
                                "Google Plus"   =>'google-plus',
                                "Vimeo"         =>'vimeo',
                                "Dribbble"      =>'dribbble',
                                "Youtube"       =>'youtube',
                                "Pinterest"     =>'pinterest',
                                "LinkedIn"      =>'linkedin',
                                "Instagram"     =>'instagram',
                                ),
                            'std' => 'twitter',
                            'description' => esc_html__( 'Select Social Name', 'deep'),
                        ),
                        array(
                            'type' => 'textfield',
                            'heading' => esc_html__( 'First Social URL', 'deep' ),
                            'param_name' => 'first_url',
                            'value'=>'',
                            'description' => esc_html__( 'First social URL', 'deep'),
                        ),
                        array(
                            'type' => 'dropdown',
                            'heading' => esc_html__( 'Second Social Name', 'deep' ),
                            'param_name' => 'second_social',
                            'value' => array(
                                "Twitter"=>'twitter',
                                "Facebook"=>'facebook',
                                "Google Plus"=>'google-plus',
                                "Vimeo"=>'vimeo',
                                "Dribbble"=>'dribbble',
                                "Youtube"=>'youtube',
                                "Youtube"=>'youtube',
                                "LinkedIn"=>'linkedin',
                                "Instagram"=>'instagram',
                                ),
                            'std' => 'facebook',
                            'description' => esc_html__( 'Select Social Name', 'deep'),
                        ),
                        array(
                            'type' => 'textfield',
                            'heading' => esc_html__( 'Second Social URL', 'deep' ),
                            'param_name' => 'second_url',
                            'value'=>'',
                            'description' => esc_html__( 'Second social URL', 'deep'),
                        ),
                        array(
                            'type' => 'dropdown',
                            'heading' => esc_html__( 'Third Social Name', 'deep' ),
                            'param_name' => 'third_social',
                            'value' => array(
                                "Twitter"=>'twitter',
                                "Facebook"=>'facebook',
                                "Google Plus"=>'google-plus',
                                "Vimeo"=>'vimeo',
                                "Dribbble"=>'dribbble',
                                "Youtube"=>'youtube',
                                "Pinterest"=>'pinterest',
                                "LinkedIn"=>'linkedin',
                                "Instagram"=>'instagram',
                                ),
                            'std' => 'google-plus',
                            'description' => esc_html__( 'Select Social Name', 'deep'),
                        ),
                        array(
                            'type' => 'textfield',
                            'heading' => esc_html__( 'Third Social URL', 'deep' ),
                            'param_name' => 'third_url',
                            'value'=>'',
                            'description' => esc_html__( 'Third social URL', 'deep'),
                        ),
                        array(
                            'type' => 'dropdown',
                            'heading' => esc_html__( 'Fourth Social Name', 'deep' ),
                            'param_name' => 'fourth_social',
                            'value' => array(
                                "Twitter"=>'twitter',
                                "Facebook"=>'facebook',
                                "Google Plus"=>'google-plus',
                                "Vimeo"=>'vimeo',
                                "Dribbble"=>'dribbble',
                                "Youtube"=>'youtube',
                                "Pinterest"=>'pinterest',
                                "LinkedIn"=>'linkedin',
                                "Instagram"=>'instagram',
                                ),
                            'std' => 'linkedin',
                            'description' => esc_html__( 'Select Social Name', 'deep'),
                        ),
                        array(
                            'type' => 'textfield',
                            'heading' => esc_html__( 'Fourth Social URL', 'deep' ),
                            'param_name' => 'fourth_url',
                            'value'=>'',
                            'description' => esc_html__( 'Fourth social URL', 'deep'),
                        ),
                    ),
                ),
                array(
                    'group'			=> 'Class & ID',
                    'type'			=> 'textfield',
                    'heading'		=> esc_html__( 'Extra Class', 'deep' ),
                    'param_name'	=> 'shortcodeclass',
                    'value'			=> '',
                    'edit_field_class'	=> 'vc_col-sm-6 vc_column paddingtop',
                ),
                array(
                    'group'			=> 'Class & ID',
                    'type'			=> 'textfield',
                    'heading'		=> esc_html__( 'ID', 'deep' ),
                    'param_name'	=> 'shortcodeid',
                    'value'			=> '',
                    'edit_field_class'	=> 'vc_col-sm-6 vc_column paddingtop',
                ),
            )
        )
    );