<?php
$kses = array(
	'a' => array(
		'href' => array(),
		'title' => array(),
		'target' => array(),
		),
	'br' => array(),
	'em' => array(),
	'strong' => array(),
);
vc_map( array(
    'name'			=> esc_html__( 'GoogleMaps', 'deep' ),
	'description'	=> esc_html__( 'Google Maps', 'deep' ),
    'base'			=> 'gmap',
    'icon'			=> 'webnus-google-map',
	'category'		=> esc_html__( 'Webnus Shortcodes', 'deep' ),
    'params'		=> array(
    	array(
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Map center Latitude', 'deep'),
			'description'		=> wp_kses( __('please enter map center Latitude<br/><br/>', 'deep'), $kses ),
			'param_name'		=> 'lat_center',
			'std'				=> '39.596165',
			'group'				=> esc_html__( 'Map Center', 'deep' ),
		),
		array(
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Map center Longitude', 'deep'),
			'description'		=> wp_kses( __('please enter map center Longitude<br/><br/>', 'deep'), $kses ),
			'param_name'		=> 'lon_center',
			'std'				=> '-102.810059',
			'group'				=> esc_html__( 'Map Center', 'deep' ),
		),
		array(
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Zoom', 'deep'),
			'description'		=> wp_kses( __('Default map zoom level. (1-19)<br/><br/>', 'deep'), $kses ),
			'param_name'		=> 'zoom_map',
			'std'				=> '9',
			'group'				=> esc_html__( 'Options', 'deep' ),
		),
		array(
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Zoom After click on marker', 'deep'),
			'description'		=> wp_kses( __('Default map zoom level after click on marker. (1-19)<br/><br/>', 'deep'), $kses ),
			'param_name'		=> 'zoom_click',
			'std'				=> '17',
			'group'				=> esc_html__( 'Options', 'deep' ),
		),
		array(
			'type'			=> 'checkbox',
			'heading'		=> esc_html__('Display Map Types', 'deep'),
			'description'	=> wp_kses( __('You can see Map Types <a href="https://developers.google.com/maps/documentation/javascript/maptypes" target="_blank">Here</a><br>', 'deep'), $kses ),
			'param_name'	=> 'map_type_display',
			'std'			=> 'true',
			'group'			=> esc_html__( 'Options', 'deep' ),
		),
		array(
			'type'			=> 'checkbox',
			'heading'		=> esc_html__('Select Map Types', 'deep'),
			'description'	=> wp_kses( __('Select your map type.<br/><br/>', 'deep'), $kses ),
			'param_name'	=> 'map_type',
			'value'			=> array(
				esc_html__( 'Roadmap', 'deep' )								=> 'roadmap',
				esc_html__( 'Terrain (load with Roadmap type)', 'deep' )	=> 'terrain',
				esc_html__( 'Satellite', 'deep' )							=> 'satellite',
				esc_html__( 'Hybrid (load with Satellite type)', 'deep' )	=> 'hybrid',
			),
			'std'			=> 'roadmap',
			'group'			=> esc_html__( 'Options', 'deep' ),
			'dependency'	=> array( 'element'=>'map_type_display', 'value' => 'true' ),
		),
		array(
			'type'				=> 'checkbox',
			'heading'			=> esc_html__('Enable Draggable feature', 'deep'),
			'description'		=> wp_kses( __('Enable Draggable feature. see <a href="https://developers.google.com/maps/documentation/javascript/markers#draggable" target="_blank">Here</a> for more information.<br/><br/>', 'deep'), $kses ),
			'std'				=> 'true',
			'param_name'		=> 'draggable',
			'group'				=> esc_html__( 'Options', 'deep' ),
			'edit_field_class'	=> 'vc_col-sm-6',
		),
		array(
			'type'				=> 'checkbox',
			'heading'			=> esc_html__('Enable Drop Animation', 'deep'),
			'std'				=> 'true',
			'description'		=> wp_kses( __('Drop Animation for markers. see <a href="https://developers.google.com/maps/documentation/javascript/examples/marker-animations" target="_blank">Here</a> for more information.<br/><br/>', 'deep'), $kses ),
			'param_name'		=> 'animation',
			'group'				=> esc_html__( 'Options', 'deep' ),
			'edit_field_class'	=> 'vc_col-sm-6',
		),
		array(
			'type'				=> 'checkbox',
			'heading'			=> esc_html__('Enable Zoom Control', 'deep'),
			'std'				=> 'true',
			'description'		=> wp_kses( __('The Zoom control displays "+" and "-" buttons for changing the zoom level of the map.<br/><br/>', 'deep'), $kses ),
			'param_name'		=> 'zoom_control_display',
			'group'				=> esc_html__( 'Options', 'deep' ),
			'edit_field_class'	=> 'vc_col-sm-6',
		),
		array(
			'type'				=> 'checkbox',
			'heading'			=> esc_html__('Enable Scrollwheel', 'deep'),
			'std'				=> 'true',
			'description'		=> wp_kses( __('This feature stops zoom in/out on your map when your page scrolls up and down from Google Maps section, so only the page will scroll.<br/><br/>', 'deep'), $kses ),
			'param_name'		=> 'scrollwheel',
			'group'				=> esc_html__( 'Options', 'deep' ),
			'edit_field_class'	=> 'vc_col-sm-6',
		),
		array(
			'type'				=> 'checkbox',
			'heading'			=> esc_html__('Enable Street View Control', 'deep'),
			'std'				=> 'true',
			'description'		=> wp_kses( __('You can see Documentation <a href="https://developers.google.com/maps/documentation/ios-sdk/streetview" target="_blank">Here</a><br/><br/>', 'deep'), $kses ),
			'param_name'		=> 'street_view',
			'group'				=> esc_html__( 'Options', 'deep' ),
			'edit_field_class'	=> 'vc_col-sm-6',
		),
		array(
			'type'				=> 'checkbox',
			'heading'			=> esc_html__('Enable Scale Control', 'deep'),
			'std'				=> 'true',
			'description'		=> wp_kses( __('You can see Documentation <a href="https://developers.google.com/maps/documentation/javascript/controls#DefaultUI" target="_blank">Here</a><br/><br/>', 'deep'), $kses ),
			'param_name'		=> 'scale_control',
			'group'				=> esc_html__( 'Options', 'deep' ),
			'edit_field_class'	=> 'vc_col-sm-6',
		),
		array(
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Width', 'deep'),
			'description'		=> wp_kses( __('Set to 0 is the full width. (0-960)<br/><br/>', 'deep'), $kses ),
			'param_name'		=> 'width',
			'std'				=> '0',
			'group'				=> esc_html__( 'Style', 'deep' ),
		),
		array(
			'type'				=> 'textfield',
			'heading'			=> esc_html__('Height', 'deep'),
			'description'		=> wp_kses( __('Default is 400.<br/><br/>', 'deep'), $kses ),
			'param_name'		=> 'height',
			'std'				=> '400',
			'group'				=> esc_html__( 'Style', 'deep' ),
		),
		array(
			'type'			=> 'dropdown',
			'heading'		=> esc_html__( 'Select Map Style', 'deep' ),
			'description'	=> esc_html__( 'if you select "Simple", you see simple map and you can select "hue" color.', 'deep'),
			'param_name'	=> 'map_style',
			'value' => array(
				'Simple'			=> 'simple',
				'Ultra Light'		=> 'light',
				'Subtle Grayscale'	=> 'gray',
				'Shade of Grey'		=> 'black',
				'Blue water'		=> 'blue',
			),
			'group'			=> esc_html__( 'Style', 'deep' ),
		),
		array(
			'type'				=> 'colorpicker',
			'heading'			=> esc_html__('Background Color', 'deep'),
			'param_name'		=> 'bg_color',
			'description'		=> wp_kses( __('Select map background color.', 'deep'), $kses ),
			'group'				=> esc_html__( 'Style', 'deep' ),
			'edit_field_class'	=> 'vc_col-sm-6',
		),
		array(
			'type'				=> 'colorpicker',
			'heading'			=> esc_html__('Hue', 'deep'),
			'param_name'		=> 'hue',
			'description'		=> wp_kses( __('You can see Hue example <a href="https://developers.google.com/maps/documentation/javascript/styling" target="_blank">Here</a><br/><br/>', 'deep'), $kses ),
			'group'				=> esc_html__( 'Style', 'deep' ),
			'dependency' => array( 
				'element'	=> 'map_style',
				'value'		=> 'simple',
			),
			'edit_field_class'	=> 'vc_col-sm-6',
		),

		array(
			'type'			=> 'dropdown',
			'heading'		=> esc_html__( 'Select Marker Type', 'deep' ),
			'description'	=> esc_html__( 'if you select "Google Default / Image", you can upload image for your marker or leave it to have deafult Google Mapss icon.', 'deep'),
			'param_name'	=> 'marker_type',
			'value' => array(
				'Google Default / Image'=>'img',
				'Radar'					=>'radar',
			),
			'group'			=> esc_html__( 'Custom Marker', 'deep' ),
		),

		array(
			'type'			=> 'colorpicker',
			'heading' 		=> esc_html__( 'Marker color', 'deep' ),
			'description' 	=> esc_html__( 'Select Marker color.', 'deep'),
			'param_name' 	=> 'marker_color',
			'value' 		=> '',
			'group'			=> esc_html__( 'Custom Marker', 'deep' ),
			'dependency' => array( 
				'element'	=> 'marker_type',
				'value'		=> 'radar',
			),
			'edit_field_class'	=> 'vc_col-sm-6',
		),


		array(
			'type'			=> 'attach_image',
			'heading'		=> esc_html__( 'Custom Marker', 'deep' ),
			'description'	=> esc_html__( 'You can select an image for your marker. if you want seperate marker for eack point, you should set it in Addresses tab.', 'deep'),
			'param_name'	=> 'custom_marker',
			'value'			=> '',
			'group'			=> esc_html__( 'Custom Marker', 'deep' ),
			'dependency' => array( 
				'element'	=> 'marker_type',
				'value'		=> 'img',
			),
		),

		array(
			'type'			=> 'dropdown',
			'heading'		=> esc_html__( 'Marker Animation', 'deep' ),
			'description'	=> esc_html__( 'You can select Drop or Bounce animation.', 'deep'),
			'param_name'	=> 'marker_animation',
			'value' 		=> array(
				'None'	=> 'none',
				'Drop'	=> 'DROP',
				'Bounce'=> 'BOUNCE',
			),
			'group'			=> esc_html__( 'Custom Marker', 'deep' ),
			'dependency' => array( 
				'element'	=> 'marker_type',
				'value'		=> 'img',
			),
		),

		array(
			'type'			=> 'param_group',
			'heading'		=> esc_html__( 'Google Maps', 'deep' ),
			'description'	=> esc_html__( ' Please Add Your Item ', 'deep' ),
			'param_name'	=> 'map_points',
			'value' 		=> '',
			'params'		=> array(
				array(
					'type'				=> 'textfield',
					'heading'			=> esc_html__( ' Latitude ', 'deep' ),
					'description'		=> esc_html__( ' Please enter your Latitude ', 'deep' ),
					'param_name'		=> 'latitude',
					'value'				=> '',
					'edit_field_class'	=> 'vc_col-sm-6',
					'admin_label'		=> true,
				),
				array(
					'type'				=> 'textfield',
					'heading'			=> esc_html__( ' Longitude ', 'deep' ),
					'description'		=> esc_html__( ' Please enter your Longitude ', 'deep' ),
					'param_name'		=> 'longitude',
					'value'				=> '',
					'edit_field_class'	=> 'vc_col-sm-6 webnus_col-sm-6',
					'admin_label'		=> true,
				),
				array(
					'type'				=> 'textarea',
					'heading'			=> esc_html__( ' Address/Info ', 'deep' ),
					'description'		=> esc_html__( ' Please enter your Address or information about this point. It Appears after click on Icon marker.', 'deep' ),
					'param_name'		=> 'address',
					'value'				=> '',
				),
				array(
					'type'				=> 'textfield',
					'heading'			=> esc_html__( ' Location Title ', 'deep' ),
					'param_name'		=> 'location_title',
					'value'				=> '',
					'edit_field_class'	=> 'vc_col-sm-6',
				),
				array(
					'type'				=> 'textfield',
					'heading'			=> esc_html__( ' Location Website ', 'deep' ),
					'param_name'		=> 'location_website',
					'value'				=> '',
					'edit_field_class'	=> 'vc_col-sm-6',
				),
				array(
					'type'			=> 'attach_image',
					'heading'		=> esc_html__( 'Custom point Marker', 'deep' ),
					'description'	=> esc_html__( 'You can select an image for your marker seperately', 'deep'),
					'param_name'	=> 'custom_marker_s',
					'value'			=> '',
				),
			),
			'group'		=> esc_html__( 'Addresses', 'deep' ),
		),

		array(
			'group'			=> 'Class & ID',
			'type'			=> 'textfield',
			'heading'		=> esc_html__( 'Extra Class', 'deep' ),
			'param_name'	=> 'shortcodeclass',
			'value'			=> '',
			'edit_field_class'	=> 'vc_col-sm-6 vc_column paddingtop',
		),
		
		array(
			'group'			=> 'Class & ID',
			'type'			=> 'textfield',
			'heading'		=> esc_html__( 'ID', 'deep' ),
			'param_name'	=> 'shortcodeid',
			'value'			=> '',
			'edit_field_class'	=> 'vc_col-sm-6 vc_column paddingtop',
		),

	),
));