<?php
if (function_exists('kc_add_map')) { 
    kc_add_map(
        array(
            'testimonial_slider' => array(
                'name'          => esc_html__( 'Testimonial Slider', 'deep' ),
                'icon'          => 'webnus-testimonialslider',
                'category'      => esc_html__( 'Webnus Shortcodes', 'deep' ),
                'params'        => array(
                    'General' => array(
                        array(
                            'name'          => 'type',
                            'label'         => esc_html__( 'Type', 'deep' ),
                            'type'          => 'select',
                            'options'       => array(
                                'mono'    => 'One',
                                'di'      => 'Two',
                                'tri'     => 'Three',
                                'tetra'   => 'Four',
                                'penta'   => 'Five',
                                'hexa'   => 'Six',
                                'hepta'   => 'Seven',
                                'octa'   => 'Eight',
                                'nona'    => 'Nine',
                                'deca'    => 'Ten',
                                'undeca'  => 'Eleven',
                                'dodeca'  => 'Twelve',
                            ),
                            'description'   => esc_html__( 'You can choose from these pre-designed types.', 'deep'),
                        ),
                        array(
                            'name'          => 'testimonial_img_octa',
                            'label'         => esc_html__( 'Background Image', 'deep' ),
                            'type'          => 'attach_image',
                            'description'   => esc_html__( 'Testimonial Image', 'deep'),
                            'relation'      => array(
                                'parent'     => 'type',
                                'show_when'  => array( 'octa' ),
                            ),
                        ),
                        array(
                            'name'          => 'testimonial_bgcolor',
                            'label'         => esc_html__('Background Color', 'deep'),
                            'type'          => 'color_picker',
                            'description'   => esc_html__('Select Background Color', 'deep'),
                            'relation'      => array(
                                'parent'     => 'type',
                                'show_when'  => array( 'octa' ),
                            ),
                        ),
                        array(
                            'type'          => 'group',
                            'label'         => esc_html__( 'Testimonial Item' , 'deep' ),
                            'description'   => esc_html__( 'Please Add Item' , 'deep' ),
                            'name'          => 'testimonial_item',
                            'options'       => array('add_text' => __('Add Item', 'deep')),
                            'relation'      => array(
                                'parent'     => 'type',
                                'hide_when'  => array( 'undeca' , 'dodeca' ),
                            ),
                            'value' => base64_encode( json_encode( array(
                                "1" => array(
                                    "testimonial_name" => "Name",                                    ),
                            ))),
                            'params' => array(
                                array(
                                    'name'          => 'testimonial_name',
                                    'label'         => esc_html__( 'Name', 'deep' ),
                                    'type'          => 'text',
                                    'description'   => esc_html__( 'Enter the Testimonial Name', 'deep'),
                                ),
                                array(
                                    'name'          => 'testimonial_img_id',
                                    'label'         => esc_html__( 'Image', 'deep' ),
                                    'type'          => 'attach_image',
                                    'description'   => esc_html__( 'Testimonial Image', 'deep'),
                                ),
                                array(
                                    'name'          => 'testimonial_subtitle',
                                    'label'         => esc_html__( 'Subtitle', 'deep' ),
                                    'type'          => 'text',
                                    'description'   => esc_html__( 'Testimonial Subtitle', 'deep'),
                                ),
                                array(
                                    'name'          => 'testimonial_content',
                                    'label'         => esc_html__( 'Content', 'deep' ),
                                    'type'          => 'textarea',
                                    'description'   => esc_html__( 'Enter the Testimonial content text', 'deep'),
                                ),
                                array(
                                    'name'          => 'testimonial_first_social',
                                    'label'         => esc_html__( 'First Social Name', 'deep' ),
                                    'type'          => 'select',
                                    'options'       => array(
                                        'twitter'       => 'Twitter',
                                        'facebook'      => 'Facebook',
                                        'google-plus'   => 'Google Plus',
                                        'vimeo'         => 'Vimeo',
                                        'dribbble'      => 'Dribbble',
                                        'youtube'       => 'Youtube',
                                        'pinterest'     => 'Pinterest',
                                        'linkedin'      => 'LinkedIn',
                                        'instagram'     => 'Instagram',
                                    ),
                                    'value'         => 'twitter',
                                    'description'   => esc_html__( 'Select Social Name', 'deep'),
                                ),
                                array(
                                    'name'          => 'testimonial_first_url',
                                    'label'         => esc_html__( 'First Social URL', 'deep' ),
                                    'type'          => 'text',
                                    'description'   => esc_html__( 'First social URL', 'deep'),
                                ),
                                array(
                                    'name'          => 'testimonial_second_social',
                                    'label'         => esc_html__( 'Second Social Name', 'deep' ),
                                    'type'          => 'select',
                                    'options'       => array(
                                        'twitter'       => 'Twitter',
                                        'facebook'      => 'Facebook',
                                        'google-plus'   => 'Google Plus',
                                        'vimeo'         => 'Vimeo',
                                        'dribbble'      => 'Dribbble',
                                        'youtube'       => 'Youtube',
                                        'pinterest'     => 'Pinterest',
                                        'linkedin'      => 'LinkedIn',
                                        'instagram'     => 'Instagram',
                                    ),
                                    'value'         => 'twitter',
                                    'description'   => esc_html__( 'Select Social Name', 'deep'),
                                ),
                                array(
                                    'name'          => 'testimonial_second_url',
                                    'label'         => esc_html__( 'Second Social URL', 'deep' ),
                                    'type'          => 'text',
                                    'description'   => esc_html__( 'Second social URL', 'deep'),
                                ),
                                array(
                                    'name'          => 'testimonial_third_social',
                                    'label'         => esc_html__( 'Third Social Name', 'deep' ),
                                    'type'          => 'select',
                                    'options'       => array(
                                        'twitter'       => 'Twitter',
                                        'facebook'      => 'Facebook',
                                        'google-plus'   => 'Google Plus',
                                        'vimeo'         => 'Vimeo',
                                        'dribbble'      => 'Dribbble',
                                        'youtube'       => 'Youtube',
                                        'pinterest'     => 'Pinterest',
                                        'linkedin'      => 'LinkedIn',
                                        'instagram'     => 'Instagram',
                                    ),
                                    'value'         => 'twitter',
                                    'description'   => esc_html__( 'Select Social Name', 'deep'),
                                ),
                                array(
                                    'name'          => 'testimonial_third_url',
                                    'label'         => esc_html__( 'Third Social URL', 'deep' ),
                                    'type'          => 'text',
                                    'description'   => esc_html__( 'Third social URL', 'deep'),
                                ),
                                array(
                                    'name'          => 'testimonial_fourth_social',
                                    'label'         => esc_html__( 'Fourth Social Name', 'deep' ),
                                    'type'          => 'select',
                                    'options'       => array(
                                        'twitter'       => 'Twitter',
                                        'facebook'      => 'Facebook',
                                        'google-plus'   => 'Google Plus',
                                        'vimeo'         => 'Vimeo',
                                        'dribbble'      => 'Dribbble',
                                        'youtube'       => 'Youtube',
                                        'pinterest'     => 'Pinterest',
                                        'linkedin'      => 'LinkedIn',
                                        'instagram'     => 'Instagram',
                                    ),
                                    'value'         => 'twitter',
                                    'description'   => esc_html__( 'Select Social Name', 'deep'),
                                ),
                                array(
                                    'name'          => 'testimonial_fourth_url',
                                    'label'         => esc_html__( 'Fourth Social URL', 'deep' ),
                                    'type'          => 'text',
                                    'description'   => esc_html__( 'Fourth social URL', 'deep'),
                                ),
                            ),
                        ),
                        array(
                            'type'          => 'group',
                            'label'         => esc_html__( 'Testimonial Item' , 'deep' ),
                            'description'   => esc_html__( 'Please Add Item' , 'deep' ),
                            'name'          => 'testimonial_item_octa',
                            'options'       => array('add_text' => __('Add Item', 'deep')),
                            'relation'      => array(
                                'parent'     => 'type',
                                'show_when'  => array( 'octa' ),
                            ),
                            'value' => base64_encode( json_encode( array(
                                "1" => array(
                                    "testimonial_name_octa" => "Name",
                                    ),
                            ))),
                            'params' => array(
                                array(
                                    'name'          => 'testimonial_name_octa',
                                    'label'         => esc_html__( 'Name', 'deep' ),
                                    'type'          => 'text',
                                    'description'   => esc_html__( 'Enter the Testimonial Name', 'deep'),
                                ),
                                array(
                                    'name'          => 'testimonial_subtitle_octa',
                                    'label'         => esc_html__( 'Subtitle', 'deep' ),
                                    'type'          => 'text',
                                    'description'   => esc_html__( 'Testimonial Subtitle', 'deep'),
                                ),
                                array(
                                    'name'          => 'testimonial_content_octa',
                                    'label'         => esc_html__( 'Content', 'deep' ),
                                    'type'          => 'textarea',
                                    'description'   => esc_html__( 'Enter the Testimonial content text', 'deep'),
                                ),
                            ),
                        ),
                        array(
                            'type'          => 'group',
                            'label'         => esc_html__( 'Testimonial Item' , 'deep' ),
                            'description'   => esc_html__( 'Please Add Item' , 'deep' ),
                            'name'          => 'testimonial_item_two',
                            'options'       => array('add_text' => __('Add Item', 'deep')),
                            'relation'      => array(
                                'parent'     => 'type',
                                'show_when'  => array( 'nona' , 'dodeca' ),
                            ),
                            'value' => base64_encode( json_encode( array(
                                "1" => array(
                                    "testimonial_name_two" => "Name",
                                    ),
                            ))),
                            'params' => array(
                                array(
                                    'name'          => 'testimonial_name_two',
                                    'label'         => esc_html__( 'Name', 'deep' ),
                                    'type'          => 'text',
                                    'description'   => esc_html__( 'Enter the Testimonial Name', 'deep'),
                                ),
                                array(
                                    'name'          => 'testimonial_img_id_two',
                                    'label'         => esc_html__( 'Image', 'deep' ),
                                    'type'          => 'attach_image',
                                    'description'   => esc_html__( 'Testimonial Image', 'deep'),
                                ),
                                array(
                                    'name'          => 'testimonial_title_two',
                                    'label'         => esc_html__( 'Title', 'deep' ),
                                    'type'          => 'text',
                                    'description'   => esc_html__( 'Testimonial Title', 'deep'),
                                ),
                                array(
                                    'name'          => 'testimonial_subtitle_two',
                                    'label'         => esc_html__( 'Subtitle', 'deep' ),
                                    'type'          => 'text',
                                    'description'   => esc_html__( 'Testimonial Subtitle', 'deep'),
                                ),
                                array(
                                    'name'          => 'testimonial_content_two',
                                    'label'         => esc_html__( 'Content', 'deep' ),
                                    'type'          => 'textarea',
                                    'description'   => esc_html__( 'Enter the Testimonial content text', 'deep'),
                                ),
                            ),
                        ),
                        array(
                            'type'          => 'group',
                            'label'         => esc_html__( 'Testimonial Item' , 'deep' ),
                            'description'   => esc_html__( 'Please Add Item' , 'deep' ),
                            'name'          => 'testimonial_item_eleven',
                            'options'       => array('add_text' => __('Add Item', 'deep')),
                            'relation'      => array(
                                'parent'     => 'type',
                                'show_when'  => array( 'undeca'  ),
                            ),
                            'params' => array(
                                array(
                                    'name'          => 'tc_content_t11',
                                    'label'         => esc_html__( 'Testimonial Content', 'deep' ),
                                    'type'          => 'textarea',
                                ),
                                array(
                                    'name'          => 'first_social',
                                    'label'         => esc_html__( 'First Social Name', 'deep' ),
                                    'type'          => 'select',
                                    'options'       => array(
                                        'twitter'       => 'Twitter',
                                        'facebook'      => 'Facebook',
                                        'google-plus'   => 'Google Plus',
                                        'vimeo'         => 'Vimeo',
                                        'dribbble'      => 'Dribbble',
                                        'youtube'       => 'Youtube',
                                        'pinterest'     => 'Pinterest',
                                        'linkedin'      => 'LinkedIn',
                                        'instagram'     => 'Instagram',
                                    ),
                                    'value'         => 'twitter',
                                    'description'   => esc_html__( 'Select Social Name', 'deep'),
                                ),
                                array(
                                    'name'          => 'first_url',
                                    'label'         => esc_html__( 'First Social URL', 'deep' ),
                                    'type'          => 'text',
                                    'description'   => esc_html__( 'First social URL', 'deep'),
                                ),
                                array(
                                    'name'          => 'second_social',
                                    'label'         => esc_html__( 'Second Social Name', 'deep' ),
                                    'type'          => 'select',
                                    'options'       => array(
                                        'twitter'       => 'Twitter',
                                        'facebook'      => 'Facebook',
                                        'google-plus'   => 'Google Plus',
                                        'vimeo'         => 'Vimeo',
                                        'dribbble'      => 'Dribbble',
                                        'youtube'       => 'Youtube',
                                        'pinterest'     => 'Pinterest',
                                        'linkedin'      => 'LinkedIn',
                                        'instagram'     => 'Instagram',
                                    ),
                                    'value'         => 'twitter',
                                    'description'   => esc_html__( 'Select Social Name', 'deep'),
                                ),
                                array(
                                    'name'          => 'second_url',
                                    'label'         => esc_html__( 'Second Social URL', 'deep' ),
                                    'type'          => 'text',
                                    'description'   => esc_html__( 'Second social URL', 'deep'),
                                ),
                                array(
                                    'name'          => 'third_social',
                                    'label'         => esc_html__( 'Third Social Name', 'deep' ),
                                    'type'          => 'select',
                                    'options'       => array(
                                        'twitter'       => 'Twitter',
                                        'facebook'      => 'Facebook',
                                        'google-plus'   => 'Google Plus',
                                        'vimeo'         => 'Vimeo',
                                        'dribbble'      => 'Dribbble',
                                        'youtube'       => 'Youtube',
                                        'pinterest'     => 'Pinterest',
                                        'linkedin'      => 'LinkedIn',
                                        'instagram'     => 'Instagram',
                                    ),
                                    'value'         => 'twitter',
                                    'description'   => esc_html__( 'Select Social Name', 'deep'),
                                ),
                                array(
                                    'name'          => 'third_url',
                                    'label'         => esc_html__( 'Third Social URL', 'deep' ),
                                    'type'          => 'text',
                                    'description'   => esc_html__( 'Third social URL', 'deep'),
                                ),
                                array(
                                    'name'          => 'fourth_social',
                                    'label'         => esc_html__( 'Fourth Social Name', 'deep' ),
                                    'type'          => 'select',
                                    'options'       => array(
                                        'twitter'       => 'Twitter',
                                        'facebook'      => 'Facebook',
                                        'google-plus'   => 'Google Plus',
                                        'vimeo'         => 'Vimeo',
                                        'dribbble'      => 'Dribbble',
                                        'youtube'       => 'Youtube',
                                        'pinterest'     => 'Pinterest',
                                        'linkedin'      => 'LinkedIn',
                                        'instagram'     => 'Instagram',
                                    ),
                                    'value'         => 'twitter',
                                    'description'   => esc_html__( 'Select Social Name', 'deep'),
                                ),
                                array(
                                    'name'          => 'fourth_url',
                                    'label'         => esc_html__( 'Fourth Social URL', 'deep' ),
                                    'type'          => 'text',
                                    'description'   => esc_html__( 'Fourth social URL', 'deep'),
                                ),
                            ),
                        ),
                    ),
                    'Class & ID' => array(
                        array(
                            'name'          => 'shortcodeclass',
                            'label'         => esc_html__('Extra Class', 'deep'),
                            'type'          => 'text',
                        ),
                        array(
                            'name'          => 'shortcodeid',
                            'label'         => esc_html__('ID', 'deep'),
                            'type'          => 'text',
                        ),
                    ),
                )
            ),
        )
    ); // End add map
 } // End if